using System.Drawing;
using System.Windows.Forms;

namespace OdsAccounting
{
    partial class FrmPersianCalendar
    {
        private System.ComponentModel.IContainer? components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            mainLayout = new TableLayoutPanel();
            titleLabel = new Label();
            navigation = new TableLayoutPanel();
            previousMonthButton = new Button();
            monthSelector = new ComboBox();
            yearSelector = new NumericUpDown();
            nextMonthButton = new Button();
            dateSummary = new TableLayoutPanel();
            monthYearLabel = new Label();
            selectedDateLabel = new Label();
            daysTable = new TableLayoutPanel();
            weekdayLabel00 = new Label();
            weekdayLabel01 = new Label();
            weekdayLabel02 = new Label();
            weekdayLabel03 = new Label();
            weekdayLabel04 = new Label();
            weekdayLabel05 = new Label();
            weekdayLabel06 = new Label();
            dayButton01 = new Button();
            dayButton02 = new Button();
            dayButton03 = new Button();
            dayButton04 = new Button();
            dayButton05 = new Button();
            dayButton06 = new Button();
            dayButton07 = new Button();
            dayButton08 = new Button();
            dayButton09 = new Button();
            dayButton10 = new Button();
            dayButton11 = new Button();
            dayButton12 = new Button();
            dayButton13 = new Button();
            dayButton14 = new Button();
            dayButton15 = new Button();
            dayButton16 = new Button();
            dayButton17 = new Button();
            dayButton18 = new Button();
            dayButton19 = new Button();
            dayButton20 = new Button();
            dayButton21 = new Button();
            dayButton22 = new Button();
            dayButton23 = new Button();
            dayButton24 = new Button();
            dayButton25 = new Button();
            dayButton26 = new Button();
            dayButton27 = new Button();
            dayButton28 = new Button();
            dayButton29 = new Button();
            dayButton30 = new Button();
            dayButton31 = new Button();
            dayButton32 = new Button();
            dayButton33 = new Button();
            dayButton34 = new Button();
            dayButton35 = new Button();
            dayButton36 = new Button();
            dayButton37 = new Button();
            dayButton38 = new Button();
            dayButton39 = new Button();
            dayButton40 = new Button();
            dayButton41 = new Button();
            dayButton42 = new Button();
            actions = new FlowLayoutPanel();
            selectButton = new Button();
            todayButton = new Button();
            cancelButton = new Button();
            ((System.ComponentModel.ISupportInitialize)yearSelector).BeginInit();
            mainLayout.SuspendLayout();
            navigation.SuspendLayout();
            dateSummary.SuspendLayout();
            daysTable.SuspendLayout();
            actions.SuspendLayout();
            SuspendLayout();
            Font = new Font("B Nazanin", 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            //
            // mainLayout
            //
            mainLayout.BackColor = Color.FromArgb(246, 248, 251);
            mainLayout.ColumnCount = 1;
            mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            mainLayout.Controls.Add(titleLabel, 0, 0);
            mainLayout.Controls.Add(navigation, 0, 1);
            mainLayout.Controls.Add(dateSummary, 0, 2);
            mainLayout.Controls.Add(daysTable, 0, 3);
            mainLayout.Controls.Add(actions, 0, 4);
            mainLayout.Dock = DockStyle.Fill;
            mainLayout.Padding = new Padding(18);
            mainLayout.RightToLeft = RightToLeft.Yes;
            mainLayout.RowCount = 5;
            mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 50F));
            mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 62F));
            mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
            mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 62F));
            mainLayout.Name = "mainLayout";
            mainLayout.TabIndex = 0;
            //
            // titleLabel
            //
            titleLabel.Dock = DockStyle.Fill;
            titleLabel.Font = new Font(Font, FontStyle.Bold);
            titleLabel.ForeColor = Color.FromArgb(35, 55, 80);
            titleLabel.Name = "titleLabel";
            titleLabel.Text = "انتخاب تاریخ شمسی";
            titleLabel.TextAlign = ContentAlignment.MiddleCenter;
            //
            // navigation
            //
            navigation.BackColor = Color.White;
            navigation.ColumnCount = 4;
            navigation.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 52F));
            navigation.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            navigation.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            navigation.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 52F));
            navigation.Controls.Add(previousMonthButton, 0, 0);
            navigation.Controls.Add(monthSelector, 1, 0);
            navigation.Controls.Add(yearSelector, 2, 0);
            navigation.Controls.Add(nextMonthButton, 3, 0);
            navigation.Dock = DockStyle.Fill;
            navigation.Name = "navigation";
            navigation.Padding = new Padding(8, 4, 8, 4);
            navigation.RightToLeft = RightToLeft.Yes;
            navigation.RowCount = 1;
            navigation.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            navigation.TabIndex = 1;
            //
            // previousMonthButton
            //
            previousMonthButton.Dock = DockStyle.Fill;
            previousMonthButton.Font = new Font(Font.FontFamily, 18F, FontStyle.Bold, GraphicsUnit.Point, 178);
            previousMonthButton.Name = "previousMonthButton";
            previousMonthButton.Text = "›";
            previousMonthButton.UseVisualStyleBackColor = true;
            //
            // monthSelector
            //
            monthSelector.DropDownStyle = ComboBoxStyle.DropDownList;
            monthSelector.Dock = DockStyle.Fill;
            monthSelector.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            monthSelector.IntegralHeight = false;
            monthSelector.Items.AddRange(new object[]
            {
                "فروردین",
                "اردیبهشت",
                "خرداد",
                "تیر",
                "مرداد",
                "شهریور",
                "مهر",
                "آبان",
                "آذر",
                "دی",
                "بهمن",
                "اسفند",
            });
            monthSelector.Name = "monthSelector";
            monthSelector.RightToLeft = RightToLeft.Yes;
            monthSelector.SelectedIndex = 0;
            monthSelector.TabIndex = 2;
            //
            // yearSelector
            //
            yearSelector.Dock = DockStyle.Fill;
            yearSelector.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            yearSelector.Maximum = 9378M;
            yearSelector.Minimum = 1M;
            yearSelector.Name = "yearSelector";
            yearSelector.RightToLeft = RightToLeft.Yes;
            yearSelector.TabIndex = 3;
            yearSelector.TextAlign = HorizontalAlignment.Center;
            yearSelector.ThousandsSeparator = false;
            yearSelector.Value = 1405M;
            //
            // nextMonthButton
            //
            nextMonthButton.Dock = DockStyle.Fill;
            nextMonthButton.Font = new Font(Font.FontFamily, 18F, FontStyle.Bold, GraphicsUnit.Point, 178);
            nextMonthButton.Name = "nextMonthButton";
            nextMonthButton.Text = "‹";
            nextMonthButton.UseVisualStyleBackColor = true;
            //
            // dateSummary
            //
            dateSummary.ColumnCount = 2;
            dateSummary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            dateSummary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            dateSummary.Controls.Add(monthYearLabel, 0, 0);
            dateSummary.Controls.Add(selectedDateLabel, 1, 0);
            dateSummary.Dock = DockStyle.Fill;
            dateSummary.Name = "dateSummary";
            dateSummary.RightToLeft = RightToLeft.Yes;
            dateSummary.RowCount = 1;
            dateSummary.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            dateSummary.TabIndex = 2;
            //
            // monthYearLabel
            //
            monthYearLabel.Dock = DockStyle.Fill;
            monthYearLabel.Font = new Font(Font, FontStyle.Bold);
            monthYearLabel.ForeColor = Color.FromArgb(42, 92, 137);
            monthYearLabel.Name = "monthYearLabel";
            monthYearLabel.TextAlign = ContentAlignment.MiddleRight;
            //
            // selectedDateLabel
            //
            selectedDateLabel.Dock = DockStyle.Fill;
            selectedDateLabel.Font = new Font(Font.FontFamily, 12F, FontStyle.Regular, GraphicsUnit.Point, 178);
            selectedDateLabel.ForeColor = Color.FromArgb(94, 108, 122);
            selectedDateLabel.Name = "selectedDateLabel";
            selectedDateLabel.TextAlign = ContentAlignment.MiddleLeft;
            //
            // daysTable
            //
            daysTable.BackColor = Color.FromArgb(220, 228, 237);
            daysTable.CellBorderStyle = TableLayoutPanelCellBorderStyle.Single;
            daysTable.ColumnCount = 7;
            daysTable.Dock = DockStyle.Fill;
            daysTable.Margin = new Padding(0, 2, 0, 2);
            daysTable.Padding = new Padding(1);
            daysTable.RightToLeft = RightToLeft.Yes;
            daysTable.RowCount = 7;
            daysTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F / 7F));
            daysTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F / 7F));
            daysTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F / 7F));
            daysTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F / 7F));
            daysTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F / 7F));
            daysTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F / 7F));
            daysTable.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F / 7F));
            daysTable.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
            daysTable.RowStyles.Add(new RowStyle(SizeType.Percent, 100F / 6F));
            daysTable.RowStyles.Add(new RowStyle(SizeType.Percent, 100F / 6F));
            daysTable.RowStyles.Add(new RowStyle(SizeType.Percent, 100F / 6F));
            daysTable.RowStyles.Add(new RowStyle(SizeType.Percent, 100F / 6F));
            daysTable.RowStyles.Add(new RowStyle(SizeType.Percent, 100F / 6F));
            daysTable.RowStyles.Add(new RowStyle(SizeType.Percent, 100F / 6F));
            //
            // Weekday headers
            //
            weekdayLabel00.BackColor = Color.FromArgb(226, 235, 245);
            weekdayLabel00.Dock = DockStyle.Fill;
            weekdayLabel00.Font = new Font(Font, FontStyle.Bold);
            weekdayLabel00.ForeColor = Color.FromArgb(44, 62, 80);
            weekdayLabel00.Margin = Padding.Empty;
            weekdayLabel00.Name = "weekdayLabel00";
            weekdayLabel00.Text = "شنبه";
            weekdayLabel00.TextAlign = ContentAlignment.MiddleCenter;
            daysTable.Controls.Add(weekdayLabel00, 0, 0);
            weekdayLabel01.BackColor = Color.FromArgb(226, 235, 245);
            weekdayLabel01.Dock = DockStyle.Fill;
            weekdayLabel01.Font = new Font(Font, FontStyle.Bold);
            weekdayLabel01.ForeColor = Color.FromArgb(44, 62, 80);
            weekdayLabel01.Margin = Padding.Empty;
            weekdayLabel01.Name = "weekdayLabel01";
            weekdayLabel01.Text = "یکشنبه";
            weekdayLabel01.TextAlign = ContentAlignment.MiddleCenter;
            daysTable.Controls.Add(weekdayLabel01, 1, 0);
            weekdayLabel02.BackColor = Color.FromArgb(226, 235, 245);
            weekdayLabel02.Dock = DockStyle.Fill;
            weekdayLabel02.Font = new Font(Font, FontStyle.Bold);
            weekdayLabel02.ForeColor = Color.FromArgb(44, 62, 80);
            weekdayLabel02.Margin = Padding.Empty;
            weekdayLabel02.Name = "weekdayLabel02";
            weekdayLabel02.Text = "دوشنبه";
            weekdayLabel02.TextAlign = ContentAlignment.MiddleCenter;
            daysTable.Controls.Add(weekdayLabel02, 2, 0);
            weekdayLabel03.BackColor = Color.FromArgb(226, 235, 245);
            weekdayLabel03.Dock = DockStyle.Fill;
            weekdayLabel03.Font = new Font(Font, FontStyle.Bold);
            weekdayLabel03.ForeColor = Color.FromArgb(44, 62, 80);
            weekdayLabel03.Margin = Padding.Empty;
            weekdayLabel03.Name = "weekdayLabel03";
            weekdayLabel03.Text = "سه‌شنبه";
            weekdayLabel03.TextAlign = ContentAlignment.MiddleCenter;
            daysTable.Controls.Add(weekdayLabel03, 3, 0);
            weekdayLabel04.BackColor = Color.FromArgb(226, 235, 245);
            weekdayLabel04.Dock = DockStyle.Fill;
            weekdayLabel04.Font = new Font(Font, FontStyle.Bold);
            weekdayLabel04.ForeColor = Color.FromArgb(44, 62, 80);
            weekdayLabel04.Margin = Padding.Empty;
            weekdayLabel04.Name = "weekdayLabel04";
            weekdayLabel04.Text = "چهارشنبه";
            weekdayLabel04.TextAlign = ContentAlignment.MiddleCenter;
            daysTable.Controls.Add(weekdayLabel04, 4, 0);
            weekdayLabel05.BackColor = Color.FromArgb(226, 235, 245);
            weekdayLabel05.Dock = DockStyle.Fill;
            weekdayLabel05.Font = new Font(Font, FontStyle.Bold);
            weekdayLabel05.ForeColor = Color.FromArgb(44, 62, 80);
            weekdayLabel05.Margin = Padding.Empty;
            weekdayLabel05.Name = "weekdayLabel05";
            weekdayLabel05.Text = "پنجشنبه";
            weekdayLabel05.TextAlign = ContentAlignment.MiddleCenter;
            daysTable.Controls.Add(weekdayLabel05, 5, 0);
            weekdayLabel06.BackColor = Color.FromArgb(226, 235, 245);
            weekdayLabel06.Dock = DockStyle.Fill;
            weekdayLabel06.Font = new Font(Font, FontStyle.Bold);
            weekdayLabel06.ForeColor = Color.FromArgb(44, 62, 80);
            weekdayLabel06.Margin = Padding.Empty;
            weekdayLabel06.Name = "weekdayLabel06";
            weekdayLabel06.Text = "جمعه";
            weekdayLabel06.TextAlign = ContentAlignment.MiddleCenter;
            daysTable.Controls.Add(weekdayLabel06, 6, 0);
            //
            // Persian calendar day cells
            //
            dayButton01.BackColor = Color.White;
            dayButton01.Dock = DockStyle.Fill;
            dayButton01.FlatStyle = FlatStyle.Flat;
            dayButton01.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton01.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton01.Margin = new Padding(2);
            dayButton01.Name = "dayButton01";
            dayButton01.Text = "1";
            dayButton01.UseVisualStyleBackColor = false;
            dayButton01.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton01.FlatAppearance.BorderSize = 1;
            dayButton01.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton01, 0, 1);
            dayButton02.BackColor = Color.White;
            dayButton02.Dock = DockStyle.Fill;
            dayButton02.FlatStyle = FlatStyle.Flat;
            dayButton02.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton02.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton02.Margin = new Padding(2);
            dayButton02.Name = "dayButton02";
            dayButton02.Text = "2";
            dayButton02.UseVisualStyleBackColor = false;
            dayButton02.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton02.FlatAppearance.BorderSize = 1;
            dayButton02.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton02, 1, 1);
            dayButton03.BackColor = Color.White;
            dayButton03.Dock = DockStyle.Fill;
            dayButton03.FlatStyle = FlatStyle.Flat;
            dayButton03.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton03.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton03.Margin = new Padding(2);
            dayButton03.Name = "dayButton03";
            dayButton03.Text = "3";
            dayButton03.UseVisualStyleBackColor = false;
            dayButton03.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton03.FlatAppearance.BorderSize = 1;
            dayButton03.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton03, 2, 1);
            dayButton04.BackColor = Color.White;
            dayButton04.Dock = DockStyle.Fill;
            dayButton04.FlatStyle = FlatStyle.Flat;
            dayButton04.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton04.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton04.Margin = new Padding(2);
            dayButton04.Name = "dayButton04";
            dayButton04.Text = "4";
            dayButton04.UseVisualStyleBackColor = false;
            dayButton04.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton04.FlatAppearance.BorderSize = 1;
            dayButton04.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton04, 3, 1);
            dayButton05.BackColor = Color.White;
            dayButton05.Dock = DockStyle.Fill;
            dayButton05.FlatStyle = FlatStyle.Flat;
            dayButton05.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton05.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton05.Margin = new Padding(2);
            dayButton05.Name = "dayButton05";
            dayButton05.Text = "5";
            dayButton05.UseVisualStyleBackColor = false;
            dayButton05.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton05.FlatAppearance.BorderSize = 1;
            dayButton05.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton05, 4, 1);
            dayButton06.BackColor = Color.White;
            dayButton06.Dock = DockStyle.Fill;
            dayButton06.FlatStyle = FlatStyle.Flat;
            dayButton06.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton06.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton06.Margin = new Padding(2);
            dayButton06.Name = "dayButton06";
            dayButton06.Text = "6";
            dayButton06.UseVisualStyleBackColor = false;
            dayButton06.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton06.FlatAppearance.BorderSize = 1;
            dayButton06.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton06, 5, 1);
            dayButton07.BackColor = Color.White;
            dayButton07.Dock = DockStyle.Fill;
            dayButton07.FlatStyle = FlatStyle.Flat;
            dayButton07.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton07.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton07.Margin = new Padding(2);
            dayButton07.Name = "dayButton07";
            dayButton07.Text = "7";
            dayButton07.UseVisualStyleBackColor = false;
            dayButton07.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton07.FlatAppearance.BorderSize = 1;
            dayButton07.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton07, 6, 1);
            dayButton08.BackColor = Color.White;
            dayButton08.Dock = DockStyle.Fill;
            dayButton08.FlatStyle = FlatStyle.Flat;
            dayButton08.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton08.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton08.Margin = new Padding(2);
            dayButton08.Name = "dayButton08";
            dayButton08.Text = "8";
            dayButton08.UseVisualStyleBackColor = false;
            dayButton08.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton08.FlatAppearance.BorderSize = 1;
            dayButton08.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton08, 0, 2);
            dayButton09.BackColor = Color.White;
            dayButton09.Dock = DockStyle.Fill;
            dayButton09.FlatStyle = FlatStyle.Flat;
            dayButton09.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton09.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton09.Margin = new Padding(2);
            dayButton09.Name = "dayButton09";
            dayButton09.Text = "9";
            dayButton09.UseVisualStyleBackColor = false;
            dayButton09.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton09.FlatAppearance.BorderSize = 1;
            dayButton09.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton09, 1, 2);
            dayButton10.BackColor = Color.White;
            dayButton10.Dock = DockStyle.Fill;
            dayButton10.FlatStyle = FlatStyle.Flat;
            dayButton10.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton10.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton10.Margin = new Padding(2);
            dayButton10.Name = "dayButton10";
            dayButton10.Text = "10";
            dayButton10.UseVisualStyleBackColor = false;
            dayButton10.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton10.FlatAppearance.BorderSize = 1;
            dayButton10.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton10, 2, 2);
            dayButton11.BackColor = Color.White;
            dayButton11.Dock = DockStyle.Fill;
            dayButton11.FlatStyle = FlatStyle.Flat;
            dayButton11.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton11.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton11.Margin = new Padding(2);
            dayButton11.Name = "dayButton11";
            dayButton11.Text = "11";
            dayButton11.UseVisualStyleBackColor = false;
            dayButton11.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton11.FlatAppearance.BorderSize = 1;
            dayButton11.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton11, 3, 2);
            dayButton12.BackColor = Color.White;
            dayButton12.Dock = DockStyle.Fill;
            dayButton12.FlatStyle = FlatStyle.Flat;
            dayButton12.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton12.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton12.Margin = new Padding(2);
            dayButton12.Name = "dayButton12";
            dayButton12.Text = "12";
            dayButton12.UseVisualStyleBackColor = false;
            dayButton12.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton12.FlatAppearance.BorderSize = 1;
            dayButton12.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton12, 4, 2);
            dayButton13.BackColor = Color.White;
            dayButton13.Dock = DockStyle.Fill;
            dayButton13.FlatStyle = FlatStyle.Flat;
            dayButton13.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton13.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton13.Margin = new Padding(2);
            dayButton13.Name = "dayButton13";
            dayButton13.Text = "13";
            dayButton13.UseVisualStyleBackColor = false;
            dayButton13.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton13.FlatAppearance.BorderSize = 1;
            dayButton13.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton13, 5, 2);
            dayButton14.BackColor = Color.White;
            dayButton14.Dock = DockStyle.Fill;
            dayButton14.FlatStyle = FlatStyle.Flat;
            dayButton14.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton14.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton14.Margin = new Padding(2);
            dayButton14.Name = "dayButton14";
            dayButton14.Text = "14";
            dayButton14.UseVisualStyleBackColor = false;
            dayButton14.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton14.FlatAppearance.BorderSize = 1;
            dayButton14.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton14, 6, 2);
            dayButton15.BackColor = Color.White;
            dayButton15.Dock = DockStyle.Fill;
            dayButton15.FlatStyle = FlatStyle.Flat;
            dayButton15.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton15.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton15.Margin = new Padding(2);
            dayButton15.Name = "dayButton15";
            dayButton15.Text = "15";
            dayButton15.UseVisualStyleBackColor = false;
            dayButton15.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton15.FlatAppearance.BorderSize = 1;
            dayButton15.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton15, 0, 3);
            dayButton16.BackColor = Color.White;
            dayButton16.Dock = DockStyle.Fill;
            dayButton16.FlatStyle = FlatStyle.Flat;
            dayButton16.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton16.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton16.Margin = new Padding(2);
            dayButton16.Name = "dayButton16";
            dayButton16.Text = "16";
            dayButton16.UseVisualStyleBackColor = false;
            dayButton16.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton16.FlatAppearance.BorderSize = 1;
            dayButton16.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton16, 1, 3);
            dayButton17.BackColor = Color.White;
            dayButton17.Dock = DockStyle.Fill;
            dayButton17.FlatStyle = FlatStyle.Flat;
            dayButton17.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton17.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton17.Margin = new Padding(2);
            dayButton17.Name = "dayButton17";
            dayButton17.Text = "17";
            dayButton17.UseVisualStyleBackColor = false;
            dayButton17.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton17.FlatAppearance.BorderSize = 1;
            dayButton17.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton17, 2, 3);
            dayButton18.BackColor = Color.White;
            dayButton18.Dock = DockStyle.Fill;
            dayButton18.FlatStyle = FlatStyle.Flat;
            dayButton18.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton18.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton18.Margin = new Padding(2);
            dayButton18.Name = "dayButton18";
            dayButton18.Text = "18";
            dayButton18.UseVisualStyleBackColor = false;
            dayButton18.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton18.FlatAppearance.BorderSize = 1;
            dayButton18.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton18, 3, 3);
            dayButton19.BackColor = Color.White;
            dayButton19.Dock = DockStyle.Fill;
            dayButton19.FlatStyle = FlatStyle.Flat;
            dayButton19.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton19.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton19.Margin = new Padding(2);
            dayButton19.Name = "dayButton19";
            dayButton19.Text = "19";
            dayButton19.UseVisualStyleBackColor = false;
            dayButton19.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton19.FlatAppearance.BorderSize = 1;
            dayButton19.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton19, 4, 3);
            dayButton20.BackColor = Color.White;
            dayButton20.Dock = DockStyle.Fill;
            dayButton20.FlatStyle = FlatStyle.Flat;
            dayButton20.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton20.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton20.Margin = new Padding(2);
            dayButton20.Name = "dayButton20";
            dayButton20.Text = "20";
            dayButton20.UseVisualStyleBackColor = false;
            dayButton20.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton20.FlatAppearance.BorderSize = 1;
            dayButton20.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton20, 5, 3);
            dayButton21.BackColor = Color.White;
            dayButton21.Dock = DockStyle.Fill;
            dayButton21.FlatStyle = FlatStyle.Flat;
            dayButton21.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton21.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton21.Margin = new Padding(2);
            dayButton21.Name = "dayButton21";
            dayButton21.Text = "21";
            dayButton21.UseVisualStyleBackColor = false;
            dayButton21.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton21.FlatAppearance.BorderSize = 1;
            dayButton21.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton21, 6, 3);
            dayButton22.BackColor = Color.White;
            dayButton22.Dock = DockStyle.Fill;
            dayButton22.FlatStyle = FlatStyle.Flat;
            dayButton22.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton22.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton22.Margin = new Padding(2);
            dayButton22.Name = "dayButton22";
            dayButton22.Text = "22";
            dayButton22.UseVisualStyleBackColor = false;
            dayButton22.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton22.FlatAppearance.BorderSize = 1;
            dayButton22.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton22, 0, 4);
            dayButton23.BackColor = Color.White;
            dayButton23.Dock = DockStyle.Fill;
            dayButton23.FlatStyle = FlatStyle.Flat;
            dayButton23.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton23.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton23.Margin = new Padding(2);
            dayButton23.Name = "dayButton23";
            dayButton23.Text = "23";
            dayButton23.UseVisualStyleBackColor = false;
            dayButton23.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton23.FlatAppearance.BorderSize = 1;
            dayButton23.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton23, 1, 4);
            dayButton24.BackColor = Color.White;
            dayButton24.Dock = DockStyle.Fill;
            dayButton24.FlatStyle = FlatStyle.Flat;
            dayButton24.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton24.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton24.Margin = new Padding(2);
            dayButton24.Name = "dayButton24";
            dayButton24.Text = "24";
            dayButton24.UseVisualStyleBackColor = false;
            dayButton24.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton24.FlatAppearance.BorderSize = 1;
            dayButton24.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton24, 2, 4);
            dayButton25.BackColor = Color.White;
            dayButton25.Dock = DockStyle.Fill;
            dayButton25.FlatStyle = FlatStyle.Flat;
            dayButton25.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton25.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton25.Margin = new Padding(2);
            dayButton25.Name = "dayButton25";
            dayButton25.Text = "25";
            dayButton25.UseVisualStyleBackColor = false;
            dayButton25.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton25.FlatAppearance.BorderSize = 1;
            dayButton25.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton25, 3, 4);
            dayButton26.BackColor = Color.White;
            dayButton26.Dock = DockStyle.Fill;
            dayButton26.FlatStyle = FlatStyle.Flat;
            dayButton26.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton26.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton26.Margin = new Padding(2);
            dayButton26.Name = "dayButton26";
            dayButton26.Text = "26";
            dayButton26.UseVisualStyleBackColor = false;
            dayButton26.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton26.FlatAppearance.BorderSize = 1;
            dayButton26.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton26, 4, 4);
            dayButton27.BackColor = Color.White;
            dayButton27.Dock = DockStyle.Fill;
            dayButton27.FlatStyle = FlatStyle.Flat;
            dayButton27.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton27.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton27.Margin = new Padding(2);
            dayButton27.Name = "dayButton27";
            dayButton27.Text = "27";
            dayButton27.UseVisualStyleBackColor = false;
            dayButton27.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton27.FlatAppearance.BorderSize = 1;
            dayButton27.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton27, 5, 4);
            dayButton28.BackColor = Color.White;
            dayButton28.Dock = DockStyle.Fill;
            dayButton28.FlatStyle = FlatStyle.Flat;
            dayButton28.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton28.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton28.Margin = new Padding(2);
            dayButton28.Name = "dayButton28";
            dayButton28.Text = "28";
            dayButton28.UseVisualStyleBackColor = false;
            dayButton28.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton28.FlatAppearance.BorderSize = 1;
            dayButton28.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton28, 6, 4);
            dayButton29.BackColor = Color.White;
            dayButton29.Dock = DockStyle.Fill;
            dayButton29.FlatStyle = FlatStyle.Flat;
            dayButton29.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton29.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton29.Margin = new Padding(2);
            dayButton29.Name = "dayButton29";
            dayButton29.Text = "29";
            dayButton29.UseVisualStyleBackColor = false;
            dayButton29.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton29.FlatAppearance.BorderSize = 1;
            dayButton29.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton29, 0, 5);
            dayButton30.BackColor = Color.White;
            dayButton30.Dock = DockStyle.Fill;
            dayButton30.FlatStyle = FlatStyle.Flat;
            dayButton30.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton30.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton30.Margin = new Padding(2);
            dayButton30.Name = "dayButton30";
            dayButton30.Text = "30";
            dayButton30.UseVisualStyleBackColor = false;
            dayButton30.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton30.FlatAppearance.BorderSize = 1;
            dayButton30.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton30, 1, 5);
            dayButton31.BackColor = Color.White;
            dayButton31.Dock = DockStyle.Fill;
            dayButton31.FlatStyle = FlatStyle.Flat;
            dayButton31.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton31.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton31.Margin = new Padding(2);
            dayButton31.Name = "dayButton31";
            dayButton31.Text = "31";
            dayButton31.UseVisualStyleBackColor = false;
            dayButton31.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton31.FlatAppearance.BorderSize = 1;
            dayButton31.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton31, 2, 5);
            dayButton32.BackColor = Color.White;
            dayButton32.Dock = DockStyle.Fill;
            dayButton32.FlatStyle = FlatStyle.Flat;
            dayButton32.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton32.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton32.Margin = new Padding(2);
            dayButton32.Name = "dayButton32";
            dayButton32.Text = "32";
            dayButton32.UseVisualStyleBackColor = false;
            dayButton32.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton32.FlatAppearance.BorderSize = 1;
            dayButton32.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton32, 3, 5);
            dayButton33.BackColor = Color.White;
            dayButton33.Dock = DockStyle.Fill;
            dayButton33.FlatStyle = FlatStyle.Flat;
            dayButton33.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton33.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton33.Margin = new Padding(2);
            dayButton33.Name = "dayButton33";
            dayButton33.Text = "33";
            dayButton33.UseVisualStyleBackColor = false;
            dayButton33.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton33.FlatAppearance.BorderSize = 1;
            dayButton33.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton33, 4, 5);
            dayButton34.BackColor = Color.White;
            dayButton34.Dock = DockStyle.Fill;
            dayButton34.FlatStyle = FlatStyle.Flat;
            dayButton34.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton34.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton34.Margin = new Padding(2);
            dayButton34.Name = "dayButton34";
            dayButton34.Text = "34";
            dayButton34.UseVisualStyleBackColor = false;
            dayButton34.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton34.FlatAppearance.BorderSize = 1;
            dayButton34.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton34, 5, 5);
            dayButton35.BackColor = Color.White;
            dayButton35.Dock = DockStyle.Fill;
            dayButton35.FlatStyle = FlatStyle.Flat;
            dayButton35.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton35.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton35.Margin = new Padding(2);
            dayButton35.Name = "dayButton35";
            dayButton35.Text = "35";
            dayButton35.UseVisualStyleBackColor = false;
            dayButton35.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton35.FlatAppearance.BorderSize = 1;
            dayButton35.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton35, 6, 5);
            dayButton36.BackColor = Color.White;
            dayButton36.Dock = DockStyle.Fill;
            dayButton36.FlatStyle = FlatStyle.Flat;
            dayButton36.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton36.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton36.Margin = new Padding(2);
            dayButton36.Name = "dayButton36";
            dayButton36.Text = "36";
            dayButton36.UseVisualStyleBackColor = false;
            dayButton36.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton36.FlatAppearance.BorderSize = 1;
            dayButton36.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton36, 0, 6);
            dayButton37.BackColor = Color.White;
            dayButton37.Dock = DockStyle.Fill;
            dayButton37.FlatStyle = FlatStyle.Flat;
            dayButton37.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton37.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton37.Margin = new Padding(2);
            dayButton37.Name = "dayButton37";
            dayButton37.Text = "37";
            dayButton37.UseVisualStyleBackColor = false;
            dayButton37.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton37.FlatAppearance.BorderSize = 1;
            dayButton37.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton37, 1, 6);
            dayButton38.BackColor = Color.White;
            dayButton38.Dock = DockStyle.Fill;
            dayButton38.FlatStyle = FlatStyle.Flat;
            dayButton38.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton38.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton38.Margin = new Padding(2);
            dayButton38.Name = "dayButton38";
            dayButton38.Text = "38";
            dayButton38.UseVisualStyleBackColor = false;
            dayButton38.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton38.FlatAppearance.BorderSize = 1;
            dayButton38.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton38, 2, 6);
            dayButton39.BackColor = Color.White;
            dayButton39.Dock = DockStyle.Fill;
            dayButton39.FlatStyle = FlatStyle.Flat;
            dayButton39.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton39.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton39.Margin = new Padding(2);
            dayButton39.Name = "dayButton39";
            dayButton39.Text = "39";
            dayButton39.UseVisualStyleBackColor = false;
            dayButton39.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton39.FlatAppearance.BorderSize = 1;
            dayButton39.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton39, 3, 6);
            dayButton40.BackColor = Color.White;
            dayButton40.Dock = DockStyle.Fill;
            dayButton40.FlatStyle = FlatStyle.Flat;
            dayButton40.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton40.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton40.Margin = new Padding(2);
            dayButton40.Name = "dayButton40";
            dayButton40.Text = "40";
            dayButton40.UseVisualStyleBackColor = false;
            dayButton40.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton40.FlatAppearance.BorderSize = 1;
            dayButton40.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton40, 4, 6);
            dayButton41.BackColor = Color.White;
            dayButton41.Dock = DockStyle.Fill;
            dayButton41.FlatStyle = FlatStyle.Flat;
            dayButton41.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton41.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton41.Margin = new Padding(2);
            dayButton41.Name = "dayButton41";
            dayButton41.Text = "41";
            dayButton41.UseVisualStyleBackColor = false;
            dayButton41.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton41.FlatAppearance.BorderSize = 1;
            dayButton41.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton41, 5, 6);
            dayButton42.BackColor = Color.White;
            dayButton42.Dock = DockStyle.Fill;
            dayButton42.FlatStyle = FlatStyle.Flat;
            dayButton42.Font = new Font(Font.FontFamily, 14F, FontStyle.Regular, GraphicsUnit.Point, 178);
            dayButton42.ForeColor = Color.FromArgb(39, 52, 67);
            dayButton42.Margin = new Padding(2);
            dayButton42.Name = "dayButton42";
            dayButton42.Text = "42";
            dayButton42.UseVisualStyleBackColor = false;
            dayButton42.FlatAppearance.BorderColor = Color.FromArgb(224, 230, 237);
            dayButton42.FlatAppearance.BorderSize = 1;
            dayButton42.FlatAppearance.MouseOverBackColor = Color.FromArgb(232, 241, 250);
            daysTable.Controls.Add(dayButton42, 6, 6);
            daysTable.Name = "daysTable";
            daysTable.TabIndex = 3;
            //
            // actions
            //
            actions.Dock = DockStyle.Fill;
            actions.FlowDirection = FlowDirection.RightToLeft;
            actions.Name = "actions";
            actions.Padding = new Padding(0, 8, 0, 0);
            actions.RightToLeft = RightToLeft.Yes;
            actions.TabIndex = 4;
            actions.WrapContents = false;
            actions.Controls.Add(selectButton);
            actions.Controls.Add(todayButton);
            actions.Controls.Add(cancelButton);
            //
            // selectButton
            //
            selectButton.BackColor = Color.FromArgb(33, 115, 100);
            selectButton.FlatAppearance.BorderSize = 0;
            selectButton.FlatStyle = FlatStyle.Flat;
            selectButton.ForeColor = Color.White;
            selectButton.Margin = new Padding(8, 0, 8, 0);
            selectButton.Name = "selectButton";
            selectButton.Size = new Size(132, 42);
            selectButton.TabIndex = 0;
            selectButton.Text = "انتخاب تاریخ";
            selectButton.UseVisualStyleBackColor = false;
            //
            // todayButton
            //
            todayButton.Margin = new Padding(8, 0, 8, 0);
            todayButton.Name = "todayButton";
            todayButton.Size = new Size(100, 42);
            todayButton.TabIndex = 1;
            todayButton.Text = "امروز";
            todayButton.UseVisualStyleBackColor = true;
            //
            // cancelButton
            //
            cancelButton.DialogResult = DialogResult.Cancel;
            cancelButton.Margin = new Padding(8, 0, 8, 0);
            cancelButton.Name = "cancelButton";
            cancelButton.Size = new Size(100, 42);
            cancelButton.TabIndex = 2;
            cancelButton.Text = "انصراف";
            cancelButton.UseVisualStyleBackColor = true;
            //
            // FrmPersianCalendar
            //
            AcceptButton = selectButton;
            AutoScaleDimensions = new SizeF(12F, 26F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(246, 248, 251);
            CancelButton = cancelButton;
            ClientSize = new Size(720, 650);
            Controls.Add(mainLayout);
            FormBorderStyle = FormBorderStyle.FixedDialog;
            MaximizeBox = false;
            MinimizeBox = false;
            Name = "FrmPersianCalendar";
            RightToLeft = RightToLeft.Yes;
            RightToLeftLayout = true;
            ShowIcon = false;
            ShowInTaskbar = false;
            StartPosition = FormStartPosition.CenterParent;
            Text = "انتخاب تاریخ شمسی";
            ((System.ComponentModel.ISupportInitialize)yearSelector).EndInit();
            actions.ResumeLayout(false);
            daysTable.ResumeLayout(false);
            dateSummary.ResumeLayout(false);
            navigation.ResumeLayout(false);
            mainLayout.ResumeLayout(false);
            ResumeLayout(false);
        }

        #endregion

        private TableLayoutPanel mainLayout = null!;
        private Label titleLabel = null!;
        private TableLayoutPanel navigation = null!;
        private Button previousMonthButton = null!;
        private ComboBox monthSelector = null!;
        private NumericUpDown yearSelector = null!;
        private Button nextMonthButton = null!;
        private TableLayoutPanel dateSummary = null!;
        private Label monthYearLabel = null!;
        private Label selectedDateLabel = null!;
        private TableLayoutPanel daysTable = null!;
        private Label weekdayLabel00 = null!;
        private Label weekdayLabel01 = null!;
        private Label weekdayLabel02 = null!;
        private Label weekdayLabel03 = null!;
        private Label weekdayLabel04 = null!;
        private Label weekdayLabel05 = null!;
        private Label weekdayLabel06 = null!;
        private Button dayButton01 = null!;
        private Button dayButton02 = null!;
        private Button dayButton03 = null!;
        private Button dayButton04 = null!;
        private Button dayButton05 = null!;
        private Button dayButton06 = null!;
        private Button dayButton07 = null!;
        private Button dayButton08 = null!;
        private Button dayButton09 = null!;
        private Button dayButton10 = null!;
        private Button dayButton11 = null!;
        private Button dayButton12 = null!;
        private Button dayButton13 = null!;
        private Button dayButton14 = null!;
        private Button dayButton15 = null!;
        private Button dayButton16 = null!;
        private Button dayButton17 = null!;
        private Button dayButton18 = null!;
        private Button dayButton19 = null!;
        private Button dayButton20 = null!;
        private Button dayButton21 = null!;
        private Button dayButton22 = null!;
        private Button dayButton23 = null!;
        private Button dayButton24 = null!;
        private Button dayButton25 = null!;
        private Button dayButton26 = null!;
        private Button dayButton27 = null!;
        private Button dayButton28 = null!;
        private Button dayButton29 = null!;
        private Button dayButton30 = null!;
        private Button dayButton31 = null!;
        private Button dayButton32 = null!;
        private Button dayButton33 = null!;
        private Button dayButton34 = null!;
        private Button dayButton35 = null!;
        private Button dayButton36 = null!;
        private Button dayButton37 = null!;
        private Button dayButton38 = null!;
        private Button dayButton39 = null!;
        private Button dayButton40 = null!;
        private Button dayButton41 = null!;
        private Button dayButton42 = null!;
        private FlowLayoutPanel actions = null!;
        private Button selectButton = null!;
        private Button todayButton = null!;
        private Button cancelButton = null!;
    }
}
