<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="FrmAddFinancialPeriod.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="FrmAddFinancialPeriod.Designer.cs">
      <DependentUpon>FrmAddFinancialPeriod.cs</DependentUpon>
    </Compile>
    <Compile Update="FrmSelectFinancialPeriod.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="FrmSelectFinancialPeriod.Designer.cs">
      <DependentUpon>FrmSelectFinancialPeriod.cs</DependentUpon>
    </Compile>
    <Compile Update="FrmPersianCalendar.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="FrmPersianCalendar.Designer.cs">
      <DependentUpon>FrmPersianCalendar.cs</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
