// فایل دیزاینر فرم - قابل ویرایش در Visual Studio Designer
using System;
using System.Drawing;
using System.Windows.Forms;

namespace OdsAccounting
{
    partial class FrmInvoice
    {
        private System.ComponentModel.IContainer components = null;
        private Panel pnlTitle;
        private FlowLayoutPanel pnlFields;
        private FlowLayoutPanel pnlButtons;
        private Panel pnlTotals;
        private SplitContainer splitMain;
        private Label lblHeader;
        private Label lblNo;
        private TextBox txtInvoiceNo;
        private Label lblDate;
        private TextBox txtInvoiceDate;
        private Label lblType;
        private ComboBox cmbType;
        private Label lblEntity;
        private ComboBox cmbEntity;
        private Label lblStatus;
        private TextBox txtStatus;
        private Button btnNew;
        private Button btnAddLine;
        private Button btnDeleteLine;
        private Button btnSave;
        private Button btnSend;
        private Button btnDelete;
        private Button btnRefresh;
        private Label lblTotals;
        private DataGridView dgvInvoices;
        private DataGridView dgvLines;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.pnlTitle = new Panel();
            this.pnlFields = new FlowLayoutPanel();
            this.pnlButtons = new FlowLayoutPanel();
            this.pnlTotals = new Panel();
            this.splitMain = new SplitContainer();
            this.lblHeader = new Label();
            this.lblNo = new Label();
            this.txtInvoiceNo = new TextBox();
            this.lblDate = new Label();
            this.txtInvoiceDate = new TextBox();
            this.lblType = new Label();
            this.cmbType = new ComboBox();
            this.lblEntity = new Label();
            this.cmbEntity = new ComboBox();
            this.lblStatus = new Label();
            this.txtStatus = new TextBox();
            this.btnNew = new Button();
            this.btnAddLine = new Button();
            this.btnDeleteLine = new Button();
            this.btnSave = new Button();
            this.btnSend = new Button();
            this.btnDelete = new Button();
            this.btnRefresh = new Button();
            this.lblTotals = new Label();
            this.dgvInvoices = new DataGridView();
            this.dgvLines = new DataGridView();
            this.SuspendLayout();
            this.pnlTitle.Dock = DockStyle.Top;
            this.pnlTitle.Height = 56;
            this.pnlTitle.BackColor = Ui.Primary;
            this.pnlFields.Dock = DockStyle.Top;
            this.pnlFields.Height = 60;
            this.pnlFields.Padding = new Padding(8, 6, 8, 6);
            this.pnlFields.AutoScroll = false;
            this.pnlButtons.Dock = DockStyle.Top;
            this.pnlButtons.Height = 56;
            this.pnlButtons.Padding = new Padding(8, 6, 8, 6);
            this.pnlButtons.AutoScroll = false;
            this.pnlTotals.Dock = DockStyle.Bottom;
            this.pnlTotals.Height = 44;
            this.pnlTotals.BackColor = Color.FromArgb(232, 240, 250);
            this.splitMain.Dock = DockStyle.Fill;
            this.splitMain.Orientation = Orientation.Horizontal;
            this.splitMain.Panel1MinSize = 120;
            this.lblHeader.Dock = DockStyle.Fill;
            this.lblHeader.Text = "صدور فاکتور و ارسال به سامانه مودیان";
            this.lblHeader.ForeColor = Color.White;
            this.lblHeader.TextAlign = ContentAlignment.MiddleCenter;
            this.lblNo.Text = "شماره فاکتور:";
            this.lblNo.AutoSize = true;
            this.lblNo.Margin = new Padding(4, 10, 4, 4);
            this.txtInvoiceNo.Width = 100;
            this.lblDate.Text = "تاریخ (شمسی):";
            this.lblDate.AutoSize = true;
            this.lblDate.Margin = new Padding(4, 10, 4, 4);
            this.txtInvoiceDate.Width = 120;
            this.lblType.Text = "نوع فاکتور:";
            this.lblType.AutoSize = true;
            this.lblType.Margin = new Padding(4, 10, 4, 4);
            this.cmbType.Width = 170;
            this.cmbType.DropDownStyle = ComboBoxStyle.DropDownList;
            this.lblEntity.Text = "خریدار/طرف حساب:";
            this.lblEntity.AutoSize = true;
            this.lblEntity.Margin = new Padding(4, 10, 4, 4);
            this.cmbEntity.Width = 260;
            this.cmbEntity.DropDownStyle = ComboBoxStyle.DropDownList;
            this.lblStatus.Text = "وضعیت:";
            this.lblStatus.AutoSize = true;
            this.lblStatus.Margin = new Padding(4, 10, 4, 4);
            this.txtStatus.Width = 140;
            this.btnNew.Text = "فاکتور جدید";
            this.btnNew.Width = 140;
            this.btnNew.Height = 38;
            this.btnNew.Margin = new Padding(4);
            this.btnNew.UseVisualStyleBackColor = false;
            this.btnNew.BackColor = Color.FromArgb(0, 84, 147);
            this.btnNew.ForeColor = Color.White;
            this.btnNew.FlatStyle = FlatStyle.Flat;
            this.btnNew.Click += BtnNew_Click;
            this.btnAddLine.Text = "افزودن ردیف";
            this.btnAddLine.Width = 140;
            this.btnAddLine.Height = 38;
            this.btnAddLine.Margin = new Padding(4);
            this.btnAddLine.UseVisualStyleBackColor = false;
            this.btnAddLine.BackColor = Color.FromArgb(0, 84, 147);
            this.btnAddLine.ForeColor = Color.White;
            this.btnAddLine.FlatStyle = FlatStyle.Flat;
            this.btnAddLine.Click += BtnAddLine_Click;
            this.btnDeleteLine.Text = "حذف ردیف";
            this.btnDeleteLine.Width = 130;
            this.btnDeleteLine.Height = 38;
            this.btnDeleteLine.Margin = new Padding(4);
            this.btnDeleteLine.UseVisualStyleBackColor = false;
            this.btnDeleteLine.BackColor = Color.FromArgb(0, 84, 147);
            this.btnDeleteLine.ForeColor = Color.White;
            this.btnDeleteLine.FlatStyle = FlatStyle.Flat;
            this.btnDeleteLine.Click += BtnDeleteLine_Click;
            this.btnSave.Text = "ذخیره";
            this.btnSave.Width = 120;
            this.btnSave.Height = 38;
            this.btnSave.Margin = new Padding(4);
            this.btnSave.UseVisualStyleBackColor = false;
            this.btnSave.BackColor = Color.FromArgb(0, 84, 147);
            this.btnSave.ForeColor = Color.White;
            this.btnSave.FlatStyle = FlatStyle.Flat;
            this.btnSave.Click += BtnSave_Click;
            this.btnSend.Text = "ارسال به مودیان";
            this.btnSend.Width = 180;
            this.btnSend.Height = 38;
            this.btnSend.Margin = new Padding(4);
            this.btnSend.UseVisualStyleBackColor = false;
            this.btnSend.BackColor = Color.FromArgb(0, 84, 147);
            this.btnSend.ForeColor = Color.White;
            this.btnSend.FlatStyle = FlatStyle.Flat;
            this.btnSend.Click += BtnSend_Click;
            this.btnDelete.Text = "حذف";
            this.btnDelete.Width = 110;
            this.btnDelete.Height = 38;
            this.btnDelete.Margin = new Padding(4);
            this.btnDelete.UseVisualStyleBackColor = false;
            this.btnDelete.BackColor = Color.FromArgb(0, 84, 147);
            this.btnDelete.ForeColor = Color.White;
            this.btnDelete.FlatStyle = FlatStyle.Flat;
            this.btnDelete.Click += BtnDelete_Click;
            this.btnRefresh.Text = "بازخوانی";
            this.btnRefresh.Width = 120;
            this.btnRefresh.Height = 38;
            this.btnRefresh.Margin = new Padding(4);
            this.btnRefresh.UseVisualStyleBackColor = false;
            this.btnRefresh.BackColor = Color.FromArgb(0, 84, 147);
            this.btnRefresh.ForeColor = Color.White;
            this.btnRefresh.FlatStyle = FlatStyle.Flat;
            this.btnRefresh.Click += BtnRefresh_Click;
            this.lblTotals.Dock = DockStyle.Fill;
            this.lblTotals.Text = "جمع کل: 0 | مالیات: 0 | قابل پرداخت: 0";
            this.lblTotals.TextAlign = ContentAlignment.MiddleCenter;
            this.dgvInvoices.Dock = DockStyle.Fill;
            this.dgvInvoices.ReadOnly = true;
            this.dgvLines.Dock = DockStyle.Fill;
            this.dgvLines.ReadOnly = true;
            // ---- ساختار کنترل‌ها ----
            this.Controls.Add(this.splitMain);
            this.Controls.Add(this.pnlTotals);
            this.Controls.Add(this.pnlButtons);
            this.Controls.Add(this.pnlFields);
            this.Controls.Add(this.pnlTitle);
            this.pnlTitle.Controls.Add(this.lblHeader);
            this.pnlFields.Controls.Add(this.lblNo);
            this.pnlFields.Controls.Add(this.txtInvoiceNo);
            this.pnlFields.Controls.Add(this.lblDate);
            this.pnlFields.Controls.Add(this.txtInvoiceDate);
            this.pnlFields.Controls.Add(this.lblType);
            this.pnlFields.Controls.Add(this.cmbType);
            this.pnlFields.Controls.Add(this.lblEntity);
            this.pnlFields.Controls.Add(this.cmbEntity);
            this.pnlFields.Controls.Add(this.lblStatus);
            this.pnlFields.Controls.Add(this.txtStatus);
            this.pnlButtons.Controls.Add(this.btnNew);
            this.pnlButtons.Controls.Add(this.btnAddLine);
            this.pnlButtons.Controls.Add(this.btnDeleteLine);
            this.pnlButtons.Controls.Add(this.btnSave);
            this.pnlButtons.Controls.Add(this.btnSend);
            this.pnlButtons.Controls.Add(this.btnDelete);
            this.pnlButtons.Controls.Add(this.btnRefresh);
            this.pnlTotals.Controls.Add(this.lblTotals);
            this.splitMain.Panel1.Controls.Add(this.dgvInvoices);
            this.splitMain.Panel2.Controls.Add(this.dgvLines);
            // ---- ترتیب z-order (برای Dock صحیح) ----
            this.pnlTitle.SendToBack();
            this.pnlFields.SendToBack();
            this.pnlButtons.SendToBack();
            this.pnlTotals.SendToBack();
            this.splitMain.SendToBack();
            this.lblHeader.SendToBack();
            this.lblNo.SendToBack();
            this.txtInvoiceNo.SendToBack();
            this.lblDate.SendToBack();
            this.txtInvoiceDate.SendToBack();
            this.lblType.SendToBack();
            this.cmbType.SendToBack();
            this.lblEntity.SendToBack();
            this.cmbEntity.SendToBack();
            this.lblStatus.SendToBack();
            this.txtStatus.SendToBack();
            this.btnNew.SendToBack();
            this.btnAddLine.SendToBack();
            this.btnDeleteLine.SendToBack();
            this.btnSave.SendToBack();
            this.btnSend.SendToBack();
            this.btnDelete.SendToBack();
            this.btnRefresh.SendToBack();
            this.lblTotals.SendToBack();
            this.dgvInvoices.SendToBack();
            this.dgvLines.SendToBack();
            // ---- فرم ----
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new Size(1280, 780);
            this.Name = "FrmInvoice";
            this.Text = "صدور فاکتور و ارسال به سامانه مودیان";
            this.StartPosition = FormStartPosition.CenterScreen;
            this.RightToLeft = RightToLeft.Yes;
            this.RightToLeftLayout = true;
            this.Load += FrmInvoice_Load;
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
