// فایل دیزاینر فرم - قابل ویرایش در Visual Studio Designer
using System;
using System.Drawing;
using System.Windows.Forms;

namespace OdsAccounting
{
    partial class FrmJournal
    {
        private System.ComponentModel.IContainer components = null;
        private Panel pnlTitle;
        private FlowLayoutPanel pnlFields;
        private FlowLayoutPanel pnlButtons;
        private SplitContainer splitMain;
        private Label lblHeader;
        private DataGridView dgvVouchers;
        private DataGridView dgvLines;
        private Label lblVNo;
        private TextBox txtVoucherNo;
        private Label lblVDate;
        private TextBox txtVoucherDate;
        private Label lblVDesc;
        private TextBox txtVoucherDesc;
        private Label lblVStatus;
        private TextBox txtVoucherStatus;
        private Button btnNew;
        private Button btnAddLine;
        private Button btnDeleteLine;
        private Button btnSave;
        private Button btnSubmit;
        private Button btnDelete;
        private Button btnRefresh;
        private Label lblBalance;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.pnlTitle = new Panel();
            this.pnlFields = new FlowLayoutPanel();
            this.pnlButtons = new FlowLayoutPanel();
            this.splitMain = new SplitContainer();
            this.lblHeader = new Label();
            this.dgvVouchers = new DataGridView();
            this.dgvLines = new DataGridView();
            this.lblVNo = new Label();
            this.txtVoucherNo = new TextBox();
            this.lblVDate = new Label();
            this.txtVoucherDate = new TextBox();
            this.lblVDesc = new Label();
            this.txtVoucherDesc = new TextBox();
            this.lblVStatus = new Label();
            this.txtVoucherStatus = new TextBox();
            this.btnNew = new Button();
            this.btnAddLine = new Button();
            this.btnDeleteLine = new Button();
            this.btnSave = new Button();
            this.btnSubmit = new Button();
            this.btnDelete = new Button();
            this.btnRefresh = new Button();
            this.lblBalance = new Label();
            this.SuspendLayout();
            this.pnlTitle.Dock = DockStyle.Top;
            this.pnlTitle.Height = 56;
            this.pnlTitle.BackColor = Ui.Primary;
            this.pnlFields.Dock = DockStyle.Top;
            this.pnlFields.Height = 60;
            this.pnlFields.Padding = new Padding(8, 6, 8, 6);
            this.pnlFields.AutoScroll = false;
            this.pnlButtons.Dock = DockStyle.Top;
            this.pnlButtons.Height = 56;
            this.pnlButtons.Padding = new Padding(8, 6, 8, 6);
            this.pnlButtons.AutoScroll = false;
            this.splitMain.Dock = DockStyle.Fill;
            this.splitMain.Orientation = Orientation.Horizontal;
            this.splitMain.Panel1MinSize = 120;
            this.lblHeader.Dock = DockStyle.Fill;
            this.lblHeader.Text = "اسناد حسابداری (سند روزنامه)";
            this.lblHeader.ForeColor = Color.White;
            this.lblHeader.TextAlign = ContentAlignment.MiddleCenter;
            this.dgvVouchers.Dock = DockStyle.Fill;
            this.dgvVouchers.ReadOnly = true;
            this.dgvLines.Dock = DockStyle.Fill;
            this.dgvLines.ReadOnly = true;
            this.lblVNo.Text = "شماره سند:";
            this.lblVNo.AutoSize = true;
            this.lblVNo.Margin = new Padding(4, 10, 4, 4);
            this.txtVoucherNo.Width = 100;
            this.lblVDate.Text = "تاریخ (شمسی):";
            this.lblVDate.AutoSize = true;
            this.lblVDate.Margin = new Padding(4, 10, 4, 4);
            this.txtVoucherDate.Width = 130;
            this.lblVDesc.Text = "شرح سند:";
            this.lblVDesc.AutoSize = true;
            this.lblVDesc.Margin = new Padding(4, 10, 4, 4);
            this.txtVoucherDesc.Width = 420;
            this.lblVStatus.Text = "وضعیت:";
            this.lblVStatus.AutoSize = true;
            this.lblVStatus.Margin = new Padding(4, 10, 4, 4);
            this.txtVoucherStatus.Width = 140;
            this.btnNew.Text = "سند جدید";
            this.btnNew.Width = 140;
            this.btnNew.Height = 38;
            this.btnNew.Margin = new Padding(4);
            this.btnNew.UseVisualStyleBackColor = false;
            this.btnNew.BackColor = Color.FromArgb(0, 84, 147);
            this.btnNew.ForeColor = Color.White;
            this.btnNew.FlatStyle = FlatStyle.Flat;
            this.btnNew.Click += BtnNew_Click;
            this.btnAddLine.Text = "افزودن ردیف";
            this.btnAddLine.Width = 140;
            this.btnAddLine.Height = 38;
            this.btnAddLine.Margin = new Padding(4);
            this.btnAddLine.UseVisualStyleBackColor = false;
            this.btnAddLine.BackColor = Color.FromArgb(0, 84, 147);
            this.btnAddLine.ForeColor = Color.White;
            this.btnAddLine.FlatStyle = FlatStyle.Flat;
            this.btnAddLine.Click += BtnAddLine_Click;
            this.btnDeleteLine.Text = "حذف ردیف";
            this.btnDeleteLine.Width = 130;
            this.btnDeleteLine.Height = 38;
            this.btnDeleteLine.Margin = new Padding(4);
            this.btnDeleteLine.UseVisualStyleBackColor = false;
            this.btnDeleteLine.BackColor = Color.FromArgb(0, 84, 147);
            this.btnDeleteLine.ForeColor = Color.White;
            this.btnDeleteLine.FlatStyle = FlatStyle.Flat;
            this.btnDeleteLine.Click += BtnDeleteLine_Click;
            this.btnSave.Text = "ذخیره سند";
            this.btnSave.Width = 130;
            this.btnSave.Height = 38;
            this.btnSave.Margin = new Padding(4);
            this.btnSave.UseVisualStyleBackColor = false;
            this.btnSave.BackColor = Color.FromArgb(0, 84, 147);
            this.btnSave.ForeColor = Color.White;
            this.btnSave.FlatStyle = FlatStyle.Flat;
            this.btnSave.Click += BtnSave_Click;
            this.btnSubmit.Text = "ارسال برای تایید";
            this.btnSubmit.Width = 170;
            this.btnSubmit.Height = 38;
            this.btnSubmit.Margin = new Padding(4);
            this.btnSubmit.UseVisualStyleBackColor = false;
            this.btnSubmit.BackColor = Color.FromArgb(0, 84, 147);
            this.btnSubmit.ForeColor = Color.White;
            this.btnSubmit.FlatStyle = FlatStyle.Flat;
            this.btnSubmit.Click += BtnSubmit_Click;
            this.btnDelete.Text = "حذف سند";
            this.btnDelete.Width = 130;
            this.btnDelete.Height = 38;
            this.btnDelete.Margin = new Padding(4);
            this.btnDelete.UseVisualStyleBackColor = false;
            this.btnDelete.BackColor = Color.FromArgb(0, 84, 147);
            this.btnDelete.ForeColor = Color.White;
            this.btnDelete.FlatStyle = FlatStyle.Flat;
            this.btnDelete.Click += BtnDelete_Click;
            this.btnRefresh.Text = "بازخوانی";
            this.btnRefresh.Width = 120;
            this.btnRefresh.Height = 38;
            this.btnRefresh.Margin = new Padding(4);
            this.btnRefresh.UseVisualStyleBackColor = false;
            this.btnRefresh.BackColor = Color.FromArgb(0, 84, 147);
            this.btnRefresh.ForeColor = Color.White;
            this.btnRefresh.FlatStyle = FlatStyle.Flat;
            this.btnRefresh.Click += BtnRefresh_Click;
            this.lblBalance.AutoSize = true;
            this.lblBalance.Text = "جمع بدهکار: 0 | جمع بستانکار: 0 | مانده: 0";
            this.lblBalance.Margin = new Padding(12,10,4,4);
            // ---- ساختار کنترل‌ها ----
            this.Controls.Add(this.splitMain);
            this.Controls.Add(this.pnlButtons);
            this.Controls.Add(this.pnlFields);
            this.Controls.Add(this.pnlTitle);
            this.pnlTitle.Controls.Add(this.lblHeader);
            this.splitMain.Panel1.Controls.Add(this.dgvVouchers);
            this.splitMain.Panel2.Controls.Add(this.dgvLines);
            this.pnlFields.Controls.Add(this.lblVNo);
            this.pnlFields.Controls.Add(this.txtVoucherNo);
            this.pnlFields.Controls.Add(this.lblVDate);
            this.pnlFields.Controls.Add(this.txtVoucherDate);
            this.pnlFields.Controls.Add(this.lblVDesc);
            this.pnlFields.Controls.Add(this.txtVoucherDesc);
            this.pnlFields.Controls.Add(this.lblVStatus);
            this.pnlFields.Controls.Add(this.txtVoucherStatus);
            this.pnlButtons.Controls.Add(this.btnNew);
            this.pnlButtons.Controls.Add(this.btnAddLine);
            this.pnlButtons.Controls.Add(this.btnDeleteLine);
            this.pnlButtons.Controls.Add(this.btnSave);
            this.pnlButtons.Controls.Add(this.btnSubmit);
            this.pnlButtons.Controls.Add(this.btnDelete);
            this.pnlButtons.Controls.Add(this.btnRefresh);
            this.pnlButtons.Controls.Add(this.lblBalance);
            // ---- ترتیب z-order (برای Dock صحیح) ----
            // ---- فرم ----
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new Size(1280, 780);
            this.Name = "FrmJournal";
            this.Text = "اسناد حسابداری";
            this.StartPosition = FormStartPosition.CenterScreen;
            this.RightToLeft = RightToLeft.Yes;
            this.RightToLeftLayout = true;
            this.Load += FrmJournal_Load;
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
