// فایل دیزاینر فرم - قابل ویرایش در Visual Studio Designer
using System;
using System.Drawing;
using System.Windows.Forms;

namespace OdsAccounting
{
    partial class FrmPayroll
    {
        private System.ComponentModel.IContainer components = null;
        private Panel pnlTitle;
        private FlowLayoutPanel pnlFields;
        private FlowLayoutPanel pnlButtons;
        private SplitContainer splitMain;
        private Label lblHeader;
        private DataGridView dgvEmployees;
        private DataGridView dgvPayroll;
        private Label lblEmpCode;
        private TextBox txtEmpCode;
        private Label lblEmpName;
        private TextBox txtEmpName;
        private Label lblEmpNid;
        private TextBox txtEmpNid;
        private Label lblBase;
        private TextBox txtBase;
        private Label lblHousing;
        private TextBox txtHousing;
        private Label lblFood;
        private TextBox txtFood;
        private Label lblChild;
        private TextBox txtChild;
        private CheckBox chkInsurance;
        private Label lblYear;
        private TextBox txtYear;
        private Label lblMonth;
        private ComboBox cmbMonth;
        private Button btnNewEmp;
        private Button btnSaveEmp;
        private Button btnDeleteEmp;
        private Button btnRun;
        private Button btnJournal;
        private Label lblPayTotal;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.pnlTitle = new Panel();
            this.pnlFields = new FlowLayoutPanel();
            this.pnlButtons = new FlowLayoutPanel();
            this.splitMain = new SplitContainer();
            this.lblHeader = new Label();
            this.dgvEmployees = new DataGridView();
            this.dgvPayroll = new DataGridView();
            this.lblEmpCode = new Label();
            this.txtEmpCode = new TextBox();
            this.lblEmpName = new Label();
            this.txtEmpName = new TextBox();
            this.lblEmpNid = new Label();
            this.txtEmpNid = new TextBox();
            this.lblBase = new Label();
            this.txtBase = new TextBox();
            this.lblHousing = new Label();
            this.txtHousing = new TextBox();
            this.lblFood = new Label();
            this.txtFood = new TextBox();
            this.lblChild = new Label();
            this.txtChild = new TextBox();
            this.chkInsurance = new CheckBox();
            this.lblYear = new Label();
            this.txtYear = new TextBox();
            this.lblMonth = new Label();
            this.cmbMonth = new ComboBox();
            this.btnNewEmp = new Button();
            this.btnSaveEmp = new Button();
            this.btnDeleteEmp = new Button();
            this.btnRun = new Button();
            this.btnJournal = new Button();
            this.lblPayTotal = new Label();
            this.SuspendLayout();
            this.pnlTitle.Dock = DockStyle.Top;
            this.pnlTitle.Height = 56;
            this.pnlTitle.BackColor = Ui.Primary;
            this.pnlFields.Dock = DockStyle.Top;
            this.pnlFields.Height = 110;
            this.pnlFields.Padding = new Padding(8, 6, 8, 6);
            this.pnlFields.AutoScroll = false;
            this.pnlButtons.Dock = DockStyle.Top;
            this.pnlButtons.Height = 56;
            this.pnlButtons.Padding = new Padding(8, 6, 8, 6);
            this.pnlButtons.AutoScroll = false;
            this.splitMain.Dock = DockStyle.Fill;
            this.splitMain.Orientation = Orientation.Horizontal;
            this.splitMain.Panel1MinSize = 120;
            this.lblHeader.Dock = DockStyle.Fill;
            this.lblHeader.Text = "سیستم حقوق و دستمزد";
            this.lblHeader.ForeColor = Color.White;
            this.lblHeader.TextAlign = ContentAlignment.MiddleCenter;
            this.dgvEmployees.Dock = DockStyle.Fill;
            this.dgvEmployees.ReadOnly = true;
            this.dgvPayroll.Dock = DockStyle.Fill;
            this.dgvPayroll.ReadOnly = true;
            this.lblEmpCode.Text = "کد پرسنلی:";
            this.lblEmpCode.AutoSize = true;
            this.lblEmpCode.Margin = new Padding(4, 10, 4, 4);
            this.txtEmpCode.Width = 100;
            this.lblEmpName.Text = "نام و نام خانوادگی:";
            this.lblEmpName.AutoSize = true;
            this.lblEmpName.Margin = new Padding(4, 10, 4, 4);
            this.txtEmpName.Width = 200;
            this.lblEmpNid.Text = "کد ملی:";
            this.lblEmpNid.AutoSize = true;
            this.lblEmpNid.Margin = new Padding(4, 10, 4, 4);
            this.txtEmpNid.Width = 130;
            this.lblBase.Text = "حقوق پایه:";
            this.lblBase.AutoSize = true;
            this.lblBase.Margin = new Padding(4, 10, 4, 4);
            this.txtBase.Width = 120;
            this.lblHousing.Text = "مسکن:";
            this.lblHousing.AutoSize = true;
            this.lblHousing.Margin = new Padding(4, 10, 4, 4);
            this.txtHousing.Width = 100;
            this.lblFood.Text = "خواروبار:";
            this.lblFood.AutoSize = true;
            this.lblFood.Margin = new Padding(4, 10, 4, 4);
            this.txtFood.Width = 100;
            this.lblChild.Text = "حق اولاد:";
            this.lblChild.AutoSize = true;
            this.lblChild.Margin = new Padding(4, 10, 4, 4);
            this.txtChild.Width = 100;
            this.chkInsurance.Text = "مشمول بیمه";
            this.chkInsurance.AutoSize = true;
            this.chkInsurance.Margin = new Padding(4, 8, 4, 4);
            this.lblYear.Text = "سال:";
            this.lblYear.AutoSize = true;
            this.lblYear.Margin = new Padding(4, 10, 4, 4);
            this.txtYear.Width = 70;
            this.lblMonth.Text = "ماه:";
            this.lblMonth.AutoSize = true;
            this.lblMonth.Margin = new Padding(4, 10, 4, 4);
            this.cmbMonth.Width = 80;
            this.cmbMonth.DropDownStyle = ComboBoxStyle.DropDownList;
            this.btnNewEmp.Text = "پرسنل جدید";
            this.btnNewEmp.Width = 140;
            this.btnNewEmp.Height = 38;
            this.btnNewEmp.Margin = new Padding(4);
            this.btnNewEmp.UseVisualStyleBackColor = false;
            this.btnNewEmp.BackColor = Color.FromArgb(0, 84, 147);
            this.btnNewEmp.ForeColor = Color.White;
            this.btnNewEmp.FlatStyle = FlatStyle.Flat;
            this.btnNewEmp.Click += BtnNewEmp_Click;
            this.btnSaveEmp.Text = "ذخیره پرسنل";
            this.btnSaveEmp.Width = 140;
            this.btnSaveEmp.Height = 38;
            this.btnSaveEmp.Margin = new Padding(4);
            this.btnSaveEmp.UseVisualStyleBackColor = false;
            this.btnSaveEmp.BackColor = Color.FromArgb(0, 84, 147);
            this.btnSaveEmp.ForeColor = Color.White;
            this.btnSaveEmp.FlatStyle = FlatStyle.Flat;
            this.btnSaveEmp.Click += BtnSaveEmp_Click;
            this.btnDeleteEmp.Text = "حذف پرسنل";
            this.btnDeleteEmp.Width = 130;
            this.btnDeleteEmp.Height = 38;
            this.btnDeleteEmp.Margin = new Padding(4);
            this.btnDeleteEmp.UseVisualStyleBackColor = false;
            this.btnDeleteEmp.BackColor = Color.FromArgb(0, 84, 147);
            this.btnDeleteEmp.ForeColor = Color.White;
            this.btnDeleteEmp.FlatStyle = FlatStyle.Flat;
            this.btnDeleteEmp.Click += BtnDeleteEmp_Click;
            this.btnRun.Text = "محاسبه حقوق ماه";
            this.btnRun.Width = 160;
            this.btnRun.Height = 38;
            this.btnRun.Margin = new Padding(4);
            this.btnRun.UseVisualStyleBackColor = false;
            this.btnRun.BackColor = Color.FromArgb(0, 84, 147);
            this.btnRun.ForeColor = Color.White;
            this.btnRun.FlatStyle = FlatStyle.Flat;
            this.btnRun.Click += BtnRun_Click;
            this.btnJournal.Text = "ثبت سند حقوق";
            this.btnJournal.Width = 150;
            this.btnJournal.Height = 38;
            this.btnJournal.Margin = new Padding(4);
            this.btnJournal.UseVisualStyleBackColor = false;
            this.btnJournal.BackColor = Color.FromArgb(0, 84, 147);
            this.btnJournal.ForeColor = Color.White;
            this.btnJournal.FlatStyle = FlatStyle.Flat;
            this.btnJournal.Click += BtnJournal_Click;
            this.lblPayTotal.AutoSize = true;
            this.lblPayTotal.Text = "جمع خالص پرداختی: 0";
            this.lblPayTotal.Margin = new Padding(12,10,4,4);
            // ---- ساختار کنترل‌ها ----
            this.Controls.Add(this.splitMain);
            this.Controls.Add(this.pnlButtons);
            this.Controls.Add(this.pnlFields);
            this.Controls.Add(this.pnlTitle);
            this.pnlTitle.Controls.Add(this.lblHeader);
            this.splitMain.Panel1.Controls.Add(this.dgvEmployees);
            this.splitMain.Panel2.Controls.Add(this.dgvPayroll);
            this.pnlFields.Controls.Add(this.lblEmpCode);
            this.pnlFields.Controls.Add(this.txtEmpCode);
            this.pnlFields.Controls.Add(this.lblEmpName);
            this.pnlFields.Controls.Add(this.txtEmpName);
            this.pnlFields.Controls.Add(this.lblEmpNid);
            this.pnlFields.Controls.Add(this.txtEmpNid);
            this.pnlFields.Controls.Add(this.lblBase);
            this.pnlFields.Controls.Add(this.txtBase);
            this.pnlFields.Controls.Add(this.lblHousing);
            this.pnlFields.Controls.Add(this.txtHousing);
            this.pnlFields.Controls.Add(this.lblFood);
            this.pnlFields.Controls.Add(this.txtFood);
            this.pnlFields.Controls.Add(this.lblChild);
            this.pnlFields.Controls.Add(this.txtChild);
            this.pnlFields.Controls.Add(this.chkInsurance);
            this.pnlFields.Controls.Add(this.lblYear);
            this.pnlFields.Controls.Add(this.txtYear);
            this.pnlFields.Controls.Add(this.lblMonth);
            this.pnlFields.Controls.Add(this.cmbMonth);
            this.pnlButtons.Controls.Add(this.btnNewEmp);
            this.pnlButtons.Controls.Add(this.btnSaveEmp);
            this.pnlButtons.Controls.Add(this.btnDeleteEmp);
            this.pnlButtons.Controls.Add(this.btnRun);
            this.pnlButtons.Controls.Add(this.btnJournal);
            this.pnlButtons.Controls.Add(this.lblPayTotal);
            // ---- ترتیب z-order (برای Dock صحیح) ----
            this.pnlTitle.SendToBack();
            this.pnlFields.SendToBack();
            this.pnlButtons.SendToBack();
            this.splitMain.SendToBack();
            this.lblHeader.SendToBack();
            this.dgvEmployees.SendToBack();
            this.dgvPayroll.SendToBack();
            this.lblEmpCode.SendToBack();
            this.txtEmpCode.SendToBack();
            this.lblEmpName.SendToBack();
            this.txtEmpName.SendToBack();
            this.lblEmpNid.SendToBack();
            this.txtEmpNid.SendToBack();
            this.lblBase.SendToBack();
            this.txtBase.SendToBack();
            this.lblHousing.SendToBack();
            this.txtHousing.SendToBack();
            this.lblFood.SendToBack();
            this.txtFood.SendToBack();
            this.lblChild.SendToBack();
            this.txtChild.SendToBack();
            this.chkInsurance.SendToBack();
            this.lblYear.SendToBack();
            this.txtYear.SendToBack();
            this.lblMonth.SendToBack();
            this.cmbMonth.SendToBack();
            this.btnNewEmp.SendToBack();
            this.btnSaveEmp.SendToBack();
            this.btnDeleteEmp.SendToBack();
            this.btnRun.SendToBack();
            this.btnJournal.SendToBack();
            this.lblPayTotal.SendToBack();
            // ---- فرم ----
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new Size(1280, 780);
            this.Name = "FrmPayroll";
            this.Text = "حقوق و دستمزد";
            this.StartPosition = FormStartPosition.CenterScreen;
            this.RightToLeft = RightToLeft.Yes;
            this.RightToLeftLayout = true;
            this.Load += FrmPayroll_Load;
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
