// فایل دیزاینر فرم - قابل ویرایش در Visual Studio Designer
using System;
using System.Drawing;
using System.Windows.Forms;

namespace OdsAccounting
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;
        private Panel pnlSidebar;
        private StatusStrip statusStrip1;
        private TabControl tabControlMain;
        private FlowLayoutPanel flowMenu;
        private Button btnMenuDashboard;
        private Button btnMenuBasic;
        private Button btnMenuChart;
        private Button btnMenuDimensions;
        private Button btnMenuJournal;
        private Button btnMenuInvoice;
        private Button btnMenuReports;
        private Button btnMenuPayroll;
        private Button btnMenuWorkflow;
        private Button btnMenuUsers;
        private Button btnMenuBackup;
        private Button btnMenuSettings;
        private Button btnMenuAI;
        private Button btnMenuExit;
        private ToolStripStatusLabel lblCompany;
        private ToolStripStatusLabel lblYear;
        private ToolStripStatusLabel lblUser;
        private ToolStripStatusLabel lblMode;
        private ToolStripStatusLabel lblDate;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.pnlSidebar = new Panel();
            this.statusStrip1 = new StatusStrip();
            this.tabControlMain = new TabControl();
            this.flowMenu = new FlowLayoutPanel();
            this.btnMenuDashboard = new Button();
            this.btnMenuBasic = new Button();
            this.btnMenuChart = new Button();
            this.btnMenuDimensions = new Button();
            this.btnMenuJournal = new Button();
            this.btnMenuInvoice = new Button();
            this.btnMenuReports = new Button();
            this.btnMenuPayroll = new Button();
            this.btnMenuWorkflow = new Button();
            this.btnMenuUsers = new Button();
            this.btnMenuBackup = new Button();
            this.btnMenuSettings = new Button();
            this.btnMenuAI = new Button();
            this.btnMenuExit = new Button();
            this.lblCompany = new ToolStripStatusLabel();
            this.lblYear = new ToolStripStatusLabel();
            this.lblUser = new ToolStripStatusLabel();
            this.lblMode = new ToolStripStatusLabel();
            this.lblDate = new ToolStripStatusLabel();
            this.SuspendLayout();
            this.pnlSidebar.Dock = DockStyle.Right;
            this.pnlSidebar.Width = 320;
            this.pnlSidebar.BackColor = Color.FromArgb(11, 37, 69);
            this.statusStrip1.Dock = DockStyle.Bottom;
            this.tabControlMain.Dock = DockStyle.Fill;
            this.flowMenu.Dock = DockStyle.Fill;
            this.flowMenu.FlowDirection = FlowDirection.TopDown;
            this.flowMenu.WrapContents = false;
            this.flowMenu.AutoScroll = true;
            this.flowMenu.BackColor = Color.FromArgb(11, 37, 69);
            this.flowMenu.Padding = new Padding(0, 6, 0, 0);
            this.btnMenuDashboard.Text = "میز کار (داشبورد)";
            this.btnMenuDashboard.Width = 300;
            this.btnMenuDashboard.Height = 46;
            this.btnMenuDashboard.Margin = new Padding(10,4,10,4);
            this.btnMenuDashboard.FlatStyle = FlatStyle.Flat;
            this.btnMenuDashboard.ForeColor = Color.White;
            this.btnMenuDashboard.BackColor = Color.FromArgb(11, 37, 69);
            this.btnMenuDashboard.TextAlign = ContentAlignment.MiddleRight;
            this.btnMenuDashboard.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuDashboard.UseVisualStyleBackColor = false;
            this.btnMenuDashboard.Tag = "Dashboard";
            this.btnMenuDashboard.Click += BtnMenu_Click;
            this.btnMenuBasic.Text = "اطلاعات پایه (شرکت و سال مالی)";
            this.btnMenuBasic.Width = 300;
            this.btnMenuBasic.Height = 46;
            this.btnMenuBasic.Margin = new Padding(10,4,10,4);
            this.btnMenuBasic.FlatStyle = FlatStyle.Flat;
            this.btnMenuBasic.ForeColor = Color.White;
            this.btnMenuBasic.BackColor = Color.FromArgb(11, 37, 69);
            this.btnMenuBasic.TextAlign = ContentAlignment.MiddleRight;
            this.btnMenuBasic.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuBasic.UseVisualStyleBackColor = false;
            this.btnMenuBasic.Tag = "Basic";
            this.btnMenuBasic.Click += BtnMenu_Click;
            this.btnMenuChart.Text = "سرفصل حساب‌ها و شناور";
            this.btnMenuChart.Width = 300;
            this.btnMenuChart.Height = 46;
            this.btnMenuChart.Margin = new Padding(10,4,10,4);
            this.btnMenuChart.FlatStyle = FlatStyle.Flat;
            this.btnMenuChart.ForeColor = Color.White;
            this.btnMenuChart.BackColor = Color.FromArgb(11, 37, 69);
            this.btnMenuChart.TextAlign = ContentAlignment.MiddleRight;
            this.btnMenuChart.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuChart.UseVisualStyleBackColor = false;
            this.btnMenuChart.Tag = "Chart";
            this.btnMenuChart.Click += BtnMenu_Click;
            this.btnMenuDimensions.Text = "مرکز هزینه و پروژه";
            this.btnMenuDimensions.Width = 300;
            this.btnMenuDimensions.Height = 46;
            this.btnMenuDimensions.Margin = new Padding(10,4,10,4);
            this.btnMenuDimensions.FlatStyle = FlatStyle.Flat;
            this.btnMenuDimensions.ForeColor = Color.White;
            this.btnMenuDimensions.BackColor = Color.FromArgb(11, 37, 69);
            this.btnMenuDimensions.TextAlign = ContentAlignment.MiddleRight;
            this.btnMenuDimensions.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuDimensions.UseVisualStyleBackColor = false;
            this.btnMenuDimensions.Tag = "Dimensions";
            this.btnMenuDimensions.Click += BtnMenu_Click;
            this.btnMenuJournal.Text = "اسناد حسابداری";
            this.btnMenuJournal.Width = 300;
            this.btnMenuJournal.Height = 46;
            this.btnMenuJournal.Margin = new Padding(10,4,10,4);
            this.btnMenuJournal.FlatStyle = FlatStyle.Flat;
            this.btnMenuJournal.ForeColor = Color.White;
            this.btnMenuJournal.BackColor = Color.FromArgb(11, 37, 69);
            this.btnMenuJournal.TextAlign = ContentAlignment.MiddleRight;
            this.btnMenuJournal.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuJournal.UseVisualStyleBackColor = false;
            this.btnMenuJournal.Tag = "Journal";
            this.btnMenuJournal.Click += BtnMenu_Click;
            this.btnMenuInvoice.Text = "صدور فاکتور و مودیان";
            this.btnMenuInvoice.Width = 300;
            this.btnMenuInvoice.Height = 46;
            this.btnMenuInvoice.Margin = new Padding(10,4,10,4);
            this.btnMenuInvoice.FlatStyle = FlatStyle.Flat;
            this.btnMenuInvoice.ForeColor = Color.White;
            this.btnMenuInvoice.BackColor = Color.FromArgb(11, 37, 69);
            this.btnMenuInvoice.TextAlign = ContentAlignment.MiddleRight;
            this.btnMenuInvoice.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuInvoice.UseVisualStyleBackColor = false;
            this.btnMenuInvoice.Tag = "Invoice";
            this.btnMenuInvoice.Click += BtnMenu_Click;
            this.btnMenuReports.Text = "گزارش‌ها و ترازها";
            this.btnMenuReports.Width = 300;
            this.btnMenuReports.Height = 46;
            this.btnMenuReports.Margin = new Padding(10,4,10,4);
            this.btnMenuReports.FlatStyle = FlatStyle.Flat;
            this.btnMenuReports.ForeColor = Color.White;
            this.btnMenuReports.BackColor = Color.FromArgb(11, 37, 69);
            this.btnMenuReports.TextAlign = ContentAlignment.MiddleRight;
            this.btnMenuReports.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuReports.UseVisualStyleBackColor = false;
            this.btnMenuReports.Tag = "Reports";
            this.btnMenuReports.Click += BtnMenu_Click;
            this.btnMenuPayroll.Text = "حقوق و دستمزد";
            this.btnMenuPayroll.Width = 300;
            this.btnMenuPayroll.Height = 46;
            this.btnMenuPayroll.Margin = new Padding(10,4,10,4);
            this.btnMenuPayroll.FlatStyle = FlatStyle.Flat;
            this.btnMenuPayroll.ForeColor = Color.White;
            this.btnMenuPayroll.BackColor = Color.FromArgb(11, 37, 69);
            this.btnMenuPayroll.TextAlign = ContentAlignment.MiddleRight;
            this.btnMenuPayroll.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuPayroll.UseVisualStyleBackColor = false;
            this.btnMenuPayroll.Tag = "Payroll";
            this.btnMenuPayroll.Click += BtnMenu_Click;
            this.btnMenuWorkflow.Text = "گردش کار و تایید";
            this.btnMenuWorkflow.Width = 300;
            this.btnMenuWorkflow.Height = 46;
            this.btnMenuWorkflow.Margin = new Padding(10,4,10,4);
            this.btnMenuWorkflow.FlatStyle = FlatStyle.Flat;
            this.btnMenuWorkflow.ForeColor = Color.White;
            this.btnMenuWorkflow.BackColor = Color.FromArgb(11, 37, 69);
            this.btnMenuWorkflow.TextAlign = ContentAlignment.MiddleRight;
            this.btnMenuWorkflow.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuWorkflow.UseVisualStyleBackColor = false;
            this.btnMenuWorkflow.Tag = "Workflow";
            this.btnMenuWorkflow.Click += BtnMenu_Click;
            this.btnMenuUsers.Text = "کاربران و امنیت";
            this.btnMenuUsers.Width = 300;
            this.btnMenuUsers.Height = 46;
            this.btnMenuUsers.Margin = new Padding(10,4,10,4);
            this.btnMenuUsers.FlatStyle = FlatStyle.Flat;
            this.btnMenuUsers.ForeColor = Color.White;
            this.btnMenuUsers.BackColor = Color.FromArgb(11, 37, 69);
            this.btnMenuUsers.TextAlign = ContentAlignment.MiddleRight;
            this.btnMenuUsers.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuUsers.UseVisualStyleBackColor = false;
            this.btnMenuUsers.Tag = "Users";
            this.btnMenuUsers.Click += BtnMenu_Click;
            this.btnMenuBackup.Text = "پشتیبان‌گیری و بازیابی";
            this.btnMenuBackup.Width = 300;
            this.btnMenuBackup.Height = 46;
            this.btnMenuBackup.Margin = new Padding(10,4,10,4);
            this.btnMenuBackup.FlatStyle = FlatStyle.Flat;
            this.btnMenuBackup.ForeColor = Color.White;
            this.btnMenuBackup.BackColor = Color.FromArgb(11, 37, 69);
            this.btnMenuBackup.TextAlign = ContentAlignment.MiddleRight;
            this.btnMenuBackup.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuBackup.UseVisualStyleBackColor = false;
            this.btnMenuBackup.Tag = "Backup";
            this.btnMenuBackup.Click += BtnMenu_Click;
            this.btnMenuSettings.Text = "تنظیمات سیستم";
            this.btnMenuSettings.Width = 300;
            this.btnMenuSettings.Height = 46;
            this.btnMenuSettings.Margin = new Padding(10,4,10,4);
            this.btnMenuSettings.FlatStyle = FlatStyle.Flat;
            this.btnMenuSettings.ForeColor = Color.White;
            this.btnMenuSettings.BackColor = Color.FromArgb(11, 37, 69);
            this.btnMenuSettings.TextAlign = ContentAlignment.MiddleRight;
            this.btnMenuSettings.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuSettings.UseVisualStyleBackColor = false;
            this.btnMenuSettings.Tag = "Settings";
            this.btnMenuSettings.Click += BtnMenu_Click;
            this.btnMenuAI.Text = "هوش مصنوعی";
            this.btnMenuAI.Width = 300;
            this.btnMenuAI.Height = 46;
            this.btnMenuAI.Margin = new Padding(10,4,10,4);
            this.btnMenuAI.FlatStyle = FlatStyle.Flat;
            this.btnMenuAI.ForeColor = Color.White;
            this.btnMenuAI.BackColor = Color.FromArgb(11, 37, 69);
            this.btnMenuAI.TextAlign = ContentAlignment.MiddleRight;
            this.btnMenuAI.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuAI.UseVisualStyleBackColor = false;
            this.btnMenuAI.Tag = "AI";
            this.btnMenuAI.Click += BtnMenu_Click;
            this.btnMenuExit.Text = "خروج";
            this.btnMenuExit.Width = 300;
            this.btnMenuExit.Height = 46;
            this.btnMenuExit.Margin = new Padding(10,4,10,4);
            this.btnMenuExit.FlatStyle = FlatStyle.Flat;
            this.btnMenuExit.ForeColor = Color.White;
            this.btnMenuExit.BackColor = Color.FromArgb(11, 37, 69);
            this.btnMenuExit.TextAlign = ContentAlignment.MiddleRight;
            this.btnMenuExit.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuExit.UseVisualStyleBackColor = false;
            this.btnMenuExit.Tag = "Exit";
            this.btnMenuExit.Click += BtnMenu_Click;
            this.lblCompany.Text = "انتخاب شرکت ...";
            this.lblYear.Text = "انتخاب سال مالی ...";
            this.lblUser.Text = "";
            this.lblMode.Text = "";
            this.lblDate.Text = "";
            // ---- ساختار کنترل‌ها ----
            // ترتیب مهم است: کنترل Fill اول، سپس StatusStrip و در آخر منوی راست (Dock Right اول پردازش می‌شود)
            this.Controls.Add(this.tabControlMain);
            this.Controls.Add(this.pnlSidebar);
            this.Controls.Add(this.statusStrip1);
            this.pnlSidebar.Controls.Add(this.flowMenu);
            this.flowMenu.Controls.Add(this.btnMenuDashboard);
            this.flowMenu.Controls.Add(this.btnMenuBasic);
            this.flowMenu.Controls.Add(this.btnMenuChart);
            this.flowMenu.Controls.Add(this.btnMenuDimensions);
            this.flowMenu.Controls.Add(this.btnMenuJournal);
            this.flowMenu.Controls.Add(this.btnMenuInvoice);
            this.flowMenu.Controls.Add(this.btnMenuReports);
            this.flowMenu.Controls.Add(this.btnMenuPayroll);
            this.flowMenu.Controls.Add(this.btnMenuWorkflow);
            this.flowMenu.Controls.Add(this.btnMenuUsers);
            this.flowMenu.Controls.Add(this.btnMenuBackup);
            this.flowMenu.Controls.Add(this.btnMenuSettings);
            this.flowMenu.Controls.Add(this.btnMenuAI);
            this.flowMenu.Controls.Add(this.btnMenuExit);
            this.statusStrip1.Items.Add(this.lblCompany);
            this.statusStrip1.Items.Add(this.lblYear);
            this.statusStrip1.Items.Add(this.lblUser);
            this.statusStrip1.Items.Add(this.lblMode);
            this.statusStrip1.Items.Add(this.lblDate);
            // ---- ترتیب z-order (برای Dock صحیح) ----
            this.flowMenu.SendToBack();
            this.btnMenuDashboard.SendToBack();
            this.btnMenuBasic.SendToBack();
            this.btnMenuChart.SendToBack();
            this.btnMenuDimensions.SendToBack();
            this.btnMenuJournal.SendToBack();
            this.btnMenuInvoice.SendToBack();
            this.btnMenuReports.SendToBack();
            this.btnMenuPayroll.SendToBack();
            this.btnMenuWorkflow.SendToBack();
            this.btnMenuUsers.SendToBack();
            this.btnMenuBackup.SendToBack();
            this.btnMenuSettings.SendToBack();
            this.btnMenuAI.SendToBack();
            this.btnMenuExit.SendToBack();
            // ---- فرم ----
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new Size(1400, 860);
            this.Name = "MainForm";
            this.Text = "نرم‌افزار حسابداری ODS";
            this.StartPosition = FormStartPosition.CenterScreen;
            this.RightToLeft = RightToLeft.Yes;
            this.RightToLeftLayout = false; // جلوگیری از آینه‌شدن Dock (Right ماندن منو در سمت راست)
            this.Load += MainForm_Load;
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
