// فایل دیزاینر فرم - قابل ویرایش در Visual Studio Designer
using System;
using System.Drawing;
using System.Windows.Forms;

namespace OdsAccounting
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;
        private Panel pnlSidebar;
        private StatusStrip statusStrip1;
        private TabControl tabControlMain;
        private System.Windows.Forms.Panel pnlMain;
        private System.Windows.Forms.Panel pnlHeader;
        private System.Windows.Forms.TableLayoutPanel tblHeader;
        private System.Windows.Forms.Panel pnlDate;
        private System.Windows.Forms.Label lblDateHeader;
        private System.Windows.Forms.Label lblCalIcon;
        private System.Windows.Forms.Panel pnlProfile;
        private System.Windows.Forms.Label lblAvatar;
        private System.Windows.Forms.Label lblUserName;
        private System.Windows.Forms.Label lblUserRole;
        private System.Windows.Forms.Panel pnlBell;
        private System.Windows.Forms.Label lblBellIcon;
        private System.Windows.Forms.Label lblBadge;
        private System.Windows.Forms.Panel pnlSearch;
        private System.Windows.Forms.TextBox txtSearch;
        private FlowLayoutPanel flowMenu;
        private Label lblSidebarHeader;
        private Button btnMenuDashboard;
        private Button btnMenuBasic;
        private Button btnMenuChart;
        private Button btnMenuDimensions;
        private Button btnMenuJournal;
        private Button btnMenuInvoice;
        private Button btnMenuReports;
        private Button btnMenuPayroll;
        private Button btnMenuWorkflow;
        private Button btnMenuUsers;
        private Button btnMenuBackup;
        private Button btnMenuSettings;
        private Button btnMenuAI;
        private Button btnMenuExit;
        private ToolStripStatusLabel lblCompany;
        private ToolStripStatusLabel lblYear;
        private ToolStripStatusLabel lblUser;
        private ToolStripStatusLabel lblMode;
        private ToolStripStatusLabel lblDate;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.pnlSidebar = new Panel();
            this.statusStrip1 = new StatusStrip();
            this.tabControlMain = new TabControl();
            this.pnlMain = new System.Windows.Forms.Panel();
            this.pnlHeader = new System.Windows.Forms.Panel();
            this.tblHeader = new System.Windows.Forms.TableLayoutPanel();
            this.pnlDate = new System.Windows.Forms.Panel();
            this.lblDateHeader = new System.Windows.Forms.Label();
            this.lblCalIcon = new System.Windows.Forms.Label();
            this.pnlProfile = new System.Windows.Forms.Panel();
            this.lblAvatar = new System.Windows.Forms.Label();
            this.lblUserName = new System.Windows.Forms.Label();
            this.lblUserRole = new System.Windows.Forms.Label();
            this.pnlBell = new System.Windows.Forms.Panel();
            this.lblBellIcon = new System.Windows.Forms.Label();
            this.lblBadge = new System.Windows.Forms.Label();
            this.pnlSearch = new System.Windows.Forms.Panel();
            this.txtSearch = new System.Windows.Forms.TextBox();
            this.flowMenu = new FlowLayoutPanel();
            this.lblSidebarHeader = new Label();
            this.btnMenuDashboard = new Button();
            this.btnMenuBasic = new Button();
            this.btnMenuChart = new Button();
            this.btnMenuDimensions = new Button();
            this.btnMenuJournal = new Button();
            this.btnMenuInvoice = new Button();
            this.btnMenuReports = new Button();
            this.btnMenuPayroll = new Button();
            this.btnMenuWorkflow = new Button();
            this.btnMenuUsers = new Button();
            this.btnMenuBackup = new Button();
            this.btnMenuSettings = new Button();
            this.btnMenuAI = new Button();
            this.btnMenuExit = new Button();
            this.lblCompany = new ToolStripStatusLabel();
            this.lblYear = new ToolStripStatusLabel();
            this.lblUser = new ToolStripStatusLabel();
            this.lblMode = new ToolStripStatusLabel();
            this.lblDate = new ToolStripStatusLabel();
            this.SuspendLayout();
            this.pnlSidebar.Dock = DockStyle.Right;
            this.pnlSidebar.Width = 350;
            this.pnlSidebar.BackColor = Color.FromArgb(15, 23, 42);
            this.statusStrip1.Dock = DockStyle.Bottom;
            this.tabControlMain.Dock = DockStyle.Fill;
            // ---- ناحیه‌ی محتوا: هدر سفید بالا + تب‌ها ----
            this.pnlMain.Dock = DockStyle.Fill;
            this.pnlMain.BackColor = Color.FromArgb(248, 250, 252);
            this.pnlHeader.Dock = DockStyle.Top;
            this.pnlHeader.Height = 76;
            this.pnlHeader.BackColor = Color.White;
            this.pnlHeader.Padding = new Padding(12, 8, 12, 8);
            this.tblHeader.Dock = DockStyle.Fill;
            this.tblHeader.RightToLeft = RightToLeft.No; // ستون‌ها از چپ به راست: تاریخ چپ، جستجو راست
            this.tblHeader.ColumnCount = 4;
            this.tblHeader.RowCount = 1;
            this.tblHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 200F));
            this.tblHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 230F));
            this.tblHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 64F));
            this.tblHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.tblHeader.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.pnlDate.Dock = DockStyle.Fill;
            this.lblDateHeader.Dock = DockStyle.Fill;
            this.lblDateHeader.TextAlign = ContentAlignment.MiddleLeft;
            this.lblDateHeader.ForeColor = Color.FromArgb(30, 41, 59);
            this.lblCalIcon.Dock = DockStyle.Left;
            this.lblCalIcon.Width = 36;
            this.lblCalIcon.TextAlign = ContentAlignment.MiddleCenter;
            this.lblCalIcon.ForeColor = Color.FromArgb(37, 99, 235);
            this.pnlProfile.Dock = DockStyle.Fill;
            this.lblAvatar.Dock = DockStyle.Right;
            this.lblAvatar.Width = 46;
            this.lblAvatar.TextAlign = ContentAlignment.MiddleCenter;
            this.lblUserName.Dock = DockStyle.Top;
            this.lblUserName.Height = 26;
            this.lblUserName.TextAlign = ContentAlignment.BottomRight;
            this.lblUserName.ForeColor = Color.FromArgb(30, 41, 59);
            this.lblUserRole.Dock = DockStyle.Fill;
            this.lblUserRole.TextAlign = ContentAlignment.TopRight;
            this.lblUserRole.ForeColor = Color.FromArgb(100, 116, 139);
            this.pnlBell.Dock = DockStyle.Fill;
            this.lblBellIcon.Dock = DockStyle.Fill;
            this.lblBellIcon.TextAlign = ContentAlignment.MiddleCenter;
            this.lblBellIcon.ForeColor = Color.FromArgb(71, 85, 105);
            this.lblBadge.Size = new Size(20, 20);
            this.lblBadge.Location = new Point(36, 14);
            this.lblBadge.TextAlign = ContentAlignment.MiddleCenter;
            this.lblBadge.BackColor = Color.FromArgb(239, 68, 68);
            this.lblBadge.ForeColor = Color.White;
            this.lblBadge.Visible = false;
            this.pnlSearch.Dock = DockStyle.Fill;
            this.pnlSearch.Padding = new Padding(0, 14, 16, 14);
            this.txtSearch.Dock = DockStyle.Fill;
            this.txtSearch.BorderStyle = BorderStyle.None;
            this.txtSearch.BackColor = Color.FromArgb(241, 245, 249);
            this.txtSearch.PlaceholderText = "جستجو در ماژول‌ها، اسناد، مشتریان و ...";
            this.txtSearch.TextAlign = HorizontalAlignment.Right;
            this.txtSearch.ForeColor = Color.FromArgb(30, 41, 59);
            this.txtSearch.RightToLeft = RightToLeft.Yes;
            this.flowMenu.Dock = DockStyle.Fill;
            this.flowMenu.FlowDirection = FlowDirection.TopDown;
            this.flowMenu.WrapContents = false;
            this.flowMenu.AutoScroll = true;
            this.flowMenu.BackColor = Color.Transparent;
            this.flowMenu.Padding = new Padding(0, 6, 0, 0);
            this.lblSidebarHeader.Text = "ODS" + System.Environment.NewLine + "نرم افزار حسابداری";
            this.lblSidebarHeader.Dock = DockStyle.Top;
            this.lblSidebarHeader.Height = 78;
            this.lblSidebarHeader.TextAlign = ContentAlignment.MiddleCenter;
            this.lblSidebarHeader.ForeColor = Color.White;
            this.lblSidebarHeader.BackColor = Color.Transparent;
            this.lblSidebarHeader.Font = new System.Drawing.Font("Vazirmatn", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.btnMenuDashboard.Text = "میز کار (داشبورد)";
            this.btnMenuDashboard.Width = 325;
            this.btnMenuDashboard.Height = 60;
            this.btnMenuDashboard.Margin = new Padding(10,10,10,10);
            this.btnMenuDashboard.FlatStyle = FlatStyle.Flat;
            this.btnMenuDashboard.ForeColor = Color.White;
            this.btnMenuDashboard.BackColor = Color.Transparent;
            this.btnMenuDashboard.TextAlign = ContentAlignment.MiddleCenter;
            this.btnMenuDashboard.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuDashboard.UseVisualStyleBackColor = false;
            this.btnMenuDashboard.Font = new System.Drawing.Font("Vazirmatn", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.btnMenuDashboard.FlatAppearance.BorderSize = 0;
            this.btnMenuDashboard.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuDashboard.FlatAppearance.MouseDownBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuDashboard.Padding = new Padding(14, 0, 14, 0);
            this.btnMenuDashboard.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.btnMenuDashboard.Tag = "Dashboard";
            this.btnMenuDashboard.Click += BtnMenu_Click;
            this.btnMenuBasic.Text = "اطلاعات پایه (شرکت و سال مالی)";
            this.btnMenuBasic.Width = 325;
            this.btnMenuBasic.Height = 60;
            this.btnMenuBasic.Margin = new Padding(10,10,10,10);
            this.btnMenuBasic.FlatStyle = FlatStyle.Flat;
            this.btnMenuBasic.ForeColor = Color.White;
            this.btnMenuBasic.BackColor = Color.Transparent;
            this.btnMenuBasic.TextAlign = ContentAlignment.MiddleCenter;
            this.btnMenuBasic.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuBasic.UseVisualStyleBackColor = false;
            this.btnMenuBasic.Font = new System.Drawing.Font("Vazirmatn", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.btnMenuBasic.FlatAppearance.BorderSize = 0;
            this.btnMenuBasic.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuBasic.FlatAppearance.MouseDownBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuBasic.Padding = new Padding(14, 0, 14, 0);
            this.btnMenuBasic.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.btnMenuBasic.Tag = "Basic";
            this.btnMenuBasic.Click += BtnMenu_Click;
            this.btnMenuChart.Text = "سرفصل حساب‌ها و شناور";
            this.btnMenuChart.Width = 325;
            this.btnMenuChart.Height = 60;
            this.btnMenuChart.Margin = new Padding(10,10,10,10);
            this.btnMenuChart.FlatStyle = FlatStyle.Flat;
            this.btnMenuChart.ForeColor = Color.White;
            this.btnMenuChart.BackColor = Color.Transparent;
            this.btnMenuChart.TextAlign = ContentAlignment.MiddleCenter;
            this.btnMenuChart.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuChart.UseVisualStyleBackColor = false;
            this.btnMenuChart.Font = new System.Drawing.Font("Vazirmatn", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.btnMenuChart.FlatAppearance.BorderSize = 0;
            this.btnMenuChart.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuChart.FlatAppearance.MouseDownBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuChart.Padding = new Padding(14, 0, 14, 0);
            this.btnMenuChart.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.btnMenuChart.Tag = "Chart";
            this.btnMenuChart.Click += BtnMenu_Click;
            this.btnMenuDimensions.Text = "مرکز هزینه و پروژه";
            this.btnMenuDimensions.Width = 325;
            this.btnMenuDimensions.Height = 60;
            this.btnMenuDimensions.Margin = new Padding(10,10,10,10);
            this.btnMenuDimensions.FlatStyle = FlatStyle.Flat;
            this.btnMenuDimensions.ForeColor = Color.White;
            this.btnMenuDimensions.BackColor = Color.Transparent;
            this.btnMenuDimensions.TextAlign = ContentAlignment.MiddleCenter;
            this.btnMenuDimensions.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuDimensions.UseVisualStyleBackColor = false;
            this.btnMenuDimensions.Font = new System.Drawing.Font("Vazirmatn", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.btnMenuDimensions.FlatAppearance.BorderSize = 0;
            this.btnMenuDimensions.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuDimensions.FlatAppearance.MouseDownBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuDimensions.Padding = new Padding(14, 0, 14, 0);
            this.btnMenuDimensions.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.btnMenuDimensions.Tag = "Dimensions";
            this.btnMenuDimensions.Click += BtnMenu_Click;
            this.btnMenuJournal.Text = "اسناد حسابداری";
            this.btnMenuJournal.Width = 325;
            this.btnMenuJournal.Height = 60;
            this.btnMenuJournal.Margin = new Padding(10,10,10,10);
            this.btnMenuJournal.FlatStyle = FlatStyle.Flat;
            this.btnMenuJournal.ForeColor = Color.White;
            this.btnMenuJournal.BackColor = Color.Transparent;
            this.btnMenuJournal.TextAlign = ContentAlignment.MiddleCenter;
            this.btnMenuJournal.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuJournal.UseVisualStyleBackColor = false;
            this.btnMenuJournal.Font = new System.Drawing.Font("Vazirmatn", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.btnMenuJournal.FlatAppearance.BorderSize = 0;
            this.btnMenuJournal.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuJournal.FlatAppearance.MouseDownBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuJournal.Padding = new Padding(14, 0, 14, 0);
            this.btnMenuJournal.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.btnMenuJournal.Tag = "Journal";
            this.btnMenuJournal.Click += BtnMenu_Click;
            this.btnMenuInvoice.Text = "صدور فاکتور و مودیان";
            this.btnMenuInvoice.Width = 325;
            this.btnMenuInvoice.Height = 60;
            this.btnMenuInvoice.Margin = new Padding(10,10,10,10);
            this.btnMenuInvoice.FlatStyle = FlatStyle.Flat;
            this.btnMenuInvoice.ForeColor = Color.White;
            this.btnMenuInvoice.BackColor = Color.Transparent;
            this.btnMenuInvoice.TextAlign = ContentAlignment.MiddleCenter;
            this.btnMenuInvoice.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuInvoice.UseVisualStyleBackColor = false;
            this.btnMenuInvoice.Font = new System.Drawing.Font("Vazirmatn", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.btnMenuInvoice.FlatAppearance.BorderSize = 0;
            this.btnMenuInvoice.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuInvoice.FlatAppearance.MouseDownBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuInvoice.Padding = new Padding(14, 0, 14, 0);
            this.btnMenuInvoice.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.btnMenuInvoice.Tag = "Invoice";
            this.btnMenuInvoice.Click += BtnMenu_Click;
            this.btnMenuReports.Text = "گزارش‌ها و ترازها";
            this.btnMenuReports.Width = 325;
            this.btnMenuReports.Height = 60;
            this.btnMenuReports.Margin = new Padding(10,10,10,10);
            this.btnMenuReports.FlatStyle = FlatStyle.Flat;
            this.btnMenuReports.ForeColor = Color.White;
            this.btnMenuReports.BackColor = Color.Transparent;
            this.btnMenuReports.TextAlign = ContentAlignment.MiddleCenter;
            this.btnMenuReports.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuReports.UseVisualStyleBackColor = false;
            this.btnMenuReports.Font = new System.Drawing.Font("Vazirmatn", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.btnMenuReports.FlatAppearance.BorderSize = 0;
            this.btnMenuReports.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuReports.FlatAppearance.MouseDownBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuReports.Padding = new Padding(14, 0, 14, 0);
            this.btnMenuReports.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.btnMenuReports.Tag = "Reports";
            this.btnMenuReports.Click += BtnMenu_Click;
            this.btnMenuPayroll.Text = "حقوق و دستمزد";
            this.btnMenuPayroll.Width = 325;
            this.btnMenuPayroll.Height = 60;
            this.btnMenuPayroll.Margin = new Padding(10,10,10,10);
            this.btnMenuPayroll.FlatStyle = FlatStyle.Flat;
            this.btnMenuPayroll.ForeColor = Color.White;
            this.btnMenuPayroll.BackColor = Color.Transparent;
            this.btnMenuPayroll.TextAlign = ContentAlignment.MiddleCenter;
            this.btnMenuPayroll.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuPayroll.UseVisualStyleBackColor = false;
            this.btnMenuPayroll.Font = new System.Drawing.Font("Vazirmatn", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.btnMenuPayroll.FlatAppearance.BorderSize = 0;
            this.btnMenuPayroll.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuPayroll.FlatAppearance.MouseDownBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuPayroll.Padding = new Padding(14, 0, 14, 0);
            this.btnMenuPayroll.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.btnMenuPayroll.Tag = "Payroll";
            this.btnMenuPayroll.Click += BtnMenu_Click;
            this.btnMenuWorkflow.Text = "گردش کار و تایید";
            this.btnMenuWorkflow.Width = 325;
            this.btnMenuWorkflow.Height = 60;
            this.btnMenuWorkflow.Margin = new Padding(10,10,10,10);
            this.btnMenuWorkflow.FlatStyle = FlatStyle.Flat;
            this.btnMenuWorkflow.ForeColor = Color.White;
            this.btnMenuWorkflow.BackColor = Color.Transparent;
            this.btnMenuWorkflow.TextAlign = ContentAlignment.MiddleCenter;
            this.btnMenuWorkflow.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuWorkflow.UseVisualStyleBackColor = false;
            this.btnMenuWorkflow.Font = new System.Drawing.Font("Vazirmatn", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.btnMenuWorkflow.FlatAppearance.BorderSize = 0;
            this.btnMenuWorkflow.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuWorkflow.FlatAppearance.MouseDownBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuWorkflow.Padding = new Padding(14, 0, 14, 0);
            this.btnMenuWorkflow.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.btnMenuWorkflow.Tag = "Workflow";
            this.btnMenuWorkflow.Click += BtnMenu_Click;
            this.btnMenuUsers.Text = "کاربران و امنیت";
            this.btnMenuUsers.Width = 325;
            this.btnMenuUsers.Height = 60;
            this.btnMenuUsers.Margin = new Padding(10,10,10,10);
            this.btnMenuUsers.FlatStyle = FlatStyle.Flat;
            this.btnMenuUsers.ForeColor = Color.White;
            this.btnMenuUsers.BackColor = Color.Transparent;
            this.btnMenuUsers.TextAlign = ContentAlignment.MiddleCenter;
            this.btnMenuUsers.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuUsers.UseVisualStyleBackColor = false;
            this.btnMenuUsers.Font = new System.Drawing.Font("Vazirmatn", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.btnMenuUsers.FlatAppearance.BorderSize = 0;
            this.btnMenuUsers.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuUsers.FlatAppearance.MouseDownBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuUsers.Padding = new Padding(14, 0, 14, 0);
            this.btnMenuUsers.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.btnMenuUsers.Tag = "Users";
            this.btnMenuUsers.Click += BtnMenu_Click;
            this.btnMenuBackup.Text = "پشتیبان‌گیری و بازیابی";
            this.btnMenuBackup.Width = 325;
            this.btnMenuBackup.Height = 60;
            this.btnMenuBackup.Margin = new Padding(10,10,10,10);
            this.btnMenuBackup.FlatStyle = FlatStyle.Flat;
            this.btnMenuBackup.ForeColor = Color.White;
            this.btnMenuBackup.BackColor = Color.Transparent;
            this.btnMenuBackup.TextAlign = ContentAlignment.MiddleCenter;
            this.btnMenuBackup.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuBackup.UseVisualStyleBackColor = false;
            this.btnMenuBackup.Font = new System.Drawing.Font("Vazirmatn", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.btnMenuBackup.FlatAppearance.BorderSize = 0;
            this.btnMenuBackup.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuBackup.FlatAppearance.MouseDownBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuBackup.Padding = new Padding(14, 0, 14, 0);
            this.btnMenuBackup.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.btnMenuBackup.Tag = "Backup";
            this.btnMenuBackup.Click += BtnMenu_Click;
            this.btnMenuSettings.Text = "تنظیمات سیستم";
            this.btnMenuSettings.Width = 325;
            this.btnMenuSettings.Height = 60;
            this.btnMenuSettings.Margin = new Padding(10,10,10,10);
            this.btnMenuSettings.FlatStyle = FlatStyle.Flat;
            this.btnMenuSettings.ForeColor = Color.White;
            this.btnMenuSettings.BackColor = Color.Transparent;
            this.btnMenuSettings.TextAlign = ContentAlignment.MiddleCenter;
            this.btnMenuSettings.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuSettings.UseVisualStyleBackColor = false;
            this.btnMenuSettings.Font = new System.Drawing.Font("Vazirmatn", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.btnMenuSettings.FlatAppearance.BorderSize = 0;
            this.btnMenuSettings.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuSettings.FlatAppearance.MouseDownBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuSettings.Padding = new Padding(14, 0, 14, 0);
            this.btnMenuSettings.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.btnMenuSettings.Tag = "Settings";
            this.btnMenuSettings.Click += BtnMenu_Click;
            this.btnMenuAI.Text = "هوش مصنوعی";
            this.btnMenuAI.Width = 325;
            this.btnMenuAI.Height = 60;
            this.btnMenuAI.Margin = new Padding(10,10,10,10);
            this.btnMenuAI.FlatStyle = FlatStyle.Flat;
            this.btnMenuAI.ForeColor = Color.White;
            this.btnMenuAI.BackColor = Color.Transparent;
            this.btnMenuAI.TextAlign = ContentAlignment.MiddleCenter;
            this.btnMenuAI.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuAI.UseVisualStyleBackColor = false;
            this.btnMenuAI.Font = new System.Drawing.Font("Vazirmatn", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.btnMenuAI.FlatAppearance.BorderSize = 0;
            this.btnMenuAI.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuAI.FlatAppearance.MouseDownBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuAI.Padding = new Padding(14, 0, 14, 0);
            this.btnMenuAI.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.btnMenuAI.Tag = "AI";
            this.btnMenuAI.Click += BtnMenu_Click;
            this.btnMenuExit.Text = "خروج";
            this.btnMenuExit.Width = 325;
            this.btnMenuExit.Height = 60;
            this.btnMenuExit.Margin = new Padding(10,10,10,10);
            this.btnMenuExit.FlatStyle = FlatStyle.Flat;
            this.btnMenuExit.ForeColor = Color.White;
            this.btnMenuExit.BackColor = Color.Transparent;
            this.btnMenuExit.TextAlign = ContentAlignment.MiddleCenter;
            this.btnMenuExit.ImageAlign = ContentAlignment.MiddleRight;
            this.btnMenuExit.UseVisualStyleBackColor = false;
            this.btnMenuExit.Font = new System.Drawing.Font("Vazirmatn", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.btnMenuExit.FlatAppearance.BorderSize = 0;
            this.btnMenuExit.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuExit.FlatAppearance.MouseDownBackColor = Color.FromArgb(30, 58, 138);
            this.btnMenuExit.Padding = new Padding(14, 0, 14, 0);
            this.btnMenuExit.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.btnMenuExit.Tag = "Exit";
            this.btnMenuExit.Click += BtnMenu_Click;
            this.lblCompany.Text = "انتخاب شرکت ...";
            this.lblYear.Text = "انتخاب سال مالی ...";
            this.lblUser.Text = "";
            this.lblMode.Text = "";
            this.lblDate.Text = "";
            // ---- ساختار کنترل‌ها ----
            // ترتیب مهم است: کنترل Fill اول، سپس StatusStrip و در آخر منوی راست (Dock Right اول پردازش می‌شود)
            this.Controls.Add(this.pnlMain);
            this.Controls.Add(this.pnlSidebar);
            this.Controls.Add(this.statusStrip1);
            this.pnlMain.Controls.Add(this.tabControlMain);
            this.pnlMain.Controls.Add(this.pnlHeader);
            this.pnlHeader.Controls.Add(this.tblHeader);
            this.tblHeader.Controls.Add(this.pnlDate, 0, 0);
            this.tblHeader.Controls.Add(this.pnlProfile, 1, 0);
            this.tblHeader.Controls.Add(this.pnlBell, 2, 0);
            this.tblHeader.Controls.Add(this.pnlSearch, 3, 0);
            this.pnlDate.Controls.Add(this.lblDateHeader);
            this.pnlDate.Controls.Add(this.lblCalIcon);
            this.pnlProfile.Controls.Add(this.lblUserRole);
            this.pnlProfile.Controls.Add(this.lblUserName);
            this.pnlProfile.Controls.Add(this.lblAvatar);
            this.pnlBell.Controls.Add(this.lblBellIcon);
            this.pnlBell.Controls.Add(this.lblBadge);
            this.pnlSearch.Controls.Add(this.txtSearch);
            this.pnlSidebar.Controls.Add(this.flowMenu);
            this.pnlSidebar.Controls.Add(this.lblSidebarHeader);
            this.flowMenu.Controls.Add(this.btnMenuDashboard);
            this.flowMenu.Controls.Add(this.btnMenuBasic);
            this.flowMenu.Controls.Add(this.btnMenuChart);
            this.flowMenu.Controls.Add(this.btnMenuDimensions);
            this.flowMenu.Controls.Add(this.btnMenuJournal);
            this.flowMenu.Controls.Add(this.btnMenuInvoice);
            this.flowMenu.Controls.Add(this.btnMenuReports);
            this.flowMenu.Controls.Add(this.btnMenuPayroll);
            this.flowMenu.Controls.Add(this.btnMenuWorkflow);
            this.flowMenu.Controls.Add(this.btnMenuUsers);
            this.flowMenu.Controls.Add(this.btnMenuBackup);
            this.flowMenu.Controls.Add(this.btnMenuSettings);
            this.flowMenu.Controls.Add(this.btnMenuAI);
            this.flowMenu.Controls.Add(this.btnMenuExit);
            this.statusStrip1.Items.Add(this.lblCompany);
            this.statusStrip1.Items.Add(this.lblYear);
            this.statusStrip1.Items.Add(this.lblUser);
            this.statusStrip1.Items.Add(this.lblMode);
            this.statusStrip1.Items.Add(this.lblDate);
            // ---- ترتیب z-order (برای Dock صحیح) ----
            this.flowMenu.SendToBack();
            this.btnMenuDashboard.SendToBack();
            this.btnMenuBasic.SendToBack();
            this.btnMenuChart.SendToBack();
            this.btnMenuDimensions.SendToBack();
            this.btnMenuJournal.SendToBack();
            this.btnMenuInvoice.SendToBack();
            this.btnMenuReports.SendToBack();
            this.btnMenuPayroll.SendToBack();
            this.btnMenuWorkflow.SendToBack();
            this.btnMenuUsers.SendToBack();
            this.btnMenuBackup.SendToBack();
            this.btnMenuSettings.SendToBack();
            this.btnMenuAI.SendToBack();
            this.btnMenuExit.SendToBack();
            // ---- فرم ----
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new Size(1400, 860);
            this.BackColor = Color.FromArgb(248, 250, 252);
            this.Name = "MainForm";
            this.Text = "نرم‌افزار حسابداری ODS";
            this.StartPosition = FormStartPosition.CenterScreen;
            this.WindowState = FormWindowState.Maximized;
            this.RightToLeft = RightToLeft.Yes;
            this.RightToLeftLayout = false; // جلوگیری از آینه‌شدن Dock (Right ماندن منو در سمت راست)
            this.Load += MainForm_Load;
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
